### ISSUE TITLE
[typescript] Types are busted after upgrading to SDK33

### ISSUE THREAD

**Issue by alamothe** [expo/vector-icons#100]
After upgrading to SDK33, type definitions for `@expo/vector-icons` are completely busted.

For example:
```
import { Ionicons } from '@expo/vector-icons';
```
will resolve to: https://github.com/expo/vector-icons/blob/master/build/Ionicons.d.ts

But this file seems auto-generated and completely busted.

**Comment by alamothe** [comment]
Actually, `10.0.2` is busted, while `9.0.0` works... which one should we use with SDK33?

**Comment by brentvatne** [comment]
`expo install @expo/vector-icons` will install ^10 on the latest version of the `expo` package now, thanks for pointing that out.

will investigate types issue soon

**Comment by mAAdhaTTah** [comment]
I'm also getting this:

```
/node_modules/@expo/vector-icons/build/createIconSet.d.ts:2:55 - error TS7016: Could not find a declaration file for module './vendor/react-native-vector-icons/lib/create-icon-set'. '/Users/jamesdigioia/Code/blaze/frontend/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set.js' implicitly has an 'any' type.

2 export { DEFAULT_ICON_COLOR, DEFAULT_ICON_SIZE } from './vendor/react-native-vector-icons/lib/create-icon-set';

```

It looks like there are a bunch of JS files in that folder with no `.d.ts` files to go with them.

**Comment by brentvatne** [comment]
types should be in a good spot these days
