### ISSUE TITLE
Missing icons, solution no longer works

### ISSUE THREAD

**Issue by coffenbacher** [expo/vector-icons#101]
The solution to missing Ionicons from issue #69 was to use an old version of the Expo vector-icons package. As of SDK 33, that's not gonna work much longer:

```
The following APIs have moved to separate packages and importing them from the "expo" package is deprecated: Font.

1. Add correct versions of these packages to your project using:

   expo install expo-font

   If "install" is not recognized as an expo command, update your expo-cli installation.

2. Change your imports so they use specific packages instead of the "expo" package:

 - import { Font } from 'expo' -> import * as Font from 'expo-font'
```

Any ideas on workarounds? I know it's kind of a lame issue caused by Ionicons, but I'm not sure how to work around it.

**Comment by coffenbacher** [comment]
For now I just forked it and upgraded the import statements which seemed to work. I also had to upgrade the expo-font dependency to ^5.0.0.

**Comment by brentvatne** [comment]
makes sense. we don't intend on maintaining parallel versions of this package with different versions of the underlying icon fonts, so forking and modifying it as you see fit, or creating your own custom icon set from the old font family are probably your best options
