### ISSUE TITLE
Custom font loading on app startup stopped working on sdk 34 

### ISSUE THREAD

**Issue by ParAnton** [expo/vector-icons#103]
In my App.js I had prior to sdk 34

```
componentDidMount() {
    // this.loadFontsAsync();
    this.setState({ fontLoaded: true });
  }

  loadFontsAsync = async () => {
    console.log('lets load fonts');
    const result = await Expo.Font.loadAsync({
      'MyRegularFont': require('./assets/fonts/My_Icons_Regular.otf'),
      'MyLightFont': require('./assets/fonts/My_Icons_Light.otf'),
    });
    console.log('lets fonts loaded', result);
    this.setState({ fontLoaded: true });
  }
```
and it got loaded and I could use it with 

> @expo/vector-icons createIconSet
later on in my components

Now using sdk 34 it stopped working I tried to use

`import  * as Font from 'expo-font';`
But that doesn't work it says when calling createIconSet

> No source from which to load font

If I move the componentDidMount function to the component using  createIconSet it works fine
but this is not what I want.
Have I missed something do the font have to be registerred in new way now with sdk 34 or something?

**Comment by ParAnton** [comment]
I have also found out that the custom font loading stopped working on android when making a standalone app. It works fine running it in expo on the android device.
my expo diagnostics
```
Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.3.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.0 => 34.0.4 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.0 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.9
```

**Comment by brentvatne** [comment]
please share a minimal reproducible example https://stackoverflow.com/help/mcve

**Comment by gorillatron** [comment]
I am also having this issue.

```
import { Ionicons } from '@expo/vector-icons'
```

Produces faulty icons.

**Comment by halfsoft** [comment]
The same issue with fontawesome icons

**Comment by ParAnton** [comment]
> I have also found out that the custom font loading stopped working on android when making a standalone app. It works fine running it in expo on the android device.
> my expo diagnostics
> 
> ```
> Expo CLI 3.0.9 environment info:
>     System:
>       OS: macOS 10.14.6
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 12.3.0 - /usr/local/bin/node
>       Yarn: 1.16.0 - /usr/local/bin/yarn
>       npm: 6.10.2 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     IDEs:
>       Android Studio: 3.2 AI-181.5540.7.32.5056338
>       Xcode: 10.3/10G8 - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ^34.0.0 => 34.0.4 
>       react: 16.8.3 => 16.8.3 
>       react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
>       react-navigation: ^3.11.0 => 3.11.1 
>     npmGlobalPackages:
>       expo-cli: 3.0.9
> ```

After a lot of struggling, clean of caching running this script
`"clean:cache": "rm -fr $TMPDIR/metro* && rm -rf /tmp/metro-bundler-cache-* && rm -rf /tmp/haste-map-react-native-packager-*",`
 reinstalling app etc 
I could move Font.loadAsync into the componenDidMount of my App.js file again :-)

**Comment by mi-mazouz** [comment]
style not working for me!

```
_loadResourcesAsync = async () => (
    Promise.all([
        Asset.loadAsync([
            require('./onboarding/logo.png'),
            require('./onboarding/willo_device_entry.png'),
            require('./setup/connectivity/bottom_shape.png'),
            require('./setup/connectivity/handle_button_press.gif'),
            require('./setup/connectivity/loading_progress.gif'),
            require('./setup/connectivity/loading_complete.png'),
            require('./setup/profile/ring_detection_progress.gif'),
            require('./setup/profile/ring_detection_complete.png'),
            require('./setup/profile/edit/no_ring.png'),
            require('./setup/profile/edit/camera_icon.png'),
            require('./account/settings/shape-background.png'),
        ]),
        Font.loadAsync({
            ...Ionicons.font,
            'metric-medium': require('../assets/fonts/Metric-Medium.otf'),
            'metric-regular': require('../assets/fonts/Metric-Regular.otf'),
            'metric-semibold': require('../assets/fonts/Metric-Semibold.otf'),
        }),
    ]);
)
```
