### ISSUE TITLE
[TypeScript] Jest tests using '@expo/vector-icons' throw Syntax Error: Unexpected Identifier

### ISSUE THREAD

**Issue by Gi11i4m** [expo/vector-icons#105]
## 🐛 Bug Report
When testing files using the following import
```typescript
import { createIconSetFromIcoMoon } from '@expo/vector-icons';
```
the following error will be thrown
```bash
SyntaxError: Unexpected identifier
```
about this internal import
```javascript
import createIconSet from './createIconSet';
```

### Environment
```
Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.19 => 16.8.23 
      @types/react-native: ^0.57.60 => 0.57.65 
      expo: ^34.0.4 => 34.0.4 
      react: ^16.8.6 => 16.8.6 
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.11.1 => 3.11.1 
    npmGlobalPackages:
      expo-cli: 3.0.9
```

Mainly targetting the latest iOS for now.

### Steps to Reproduce
(Assuming `bash`, `expo` and `yarn` installations)
- `expo init`
- `yarn add -D ts-jest @types/jest @types/react @types/react-native`
- Use [this guide](https://kulshekhar.github.io/ts-jest/user/react-native/) to integrate ts-jest
**Apparently the bug already occurs even without ts-jest**
- Write a test that uses a file importing `{ createIconSetFromIcoMoon }` from `@expo/vector-icons`

### Expected Behavior
Tests using the `@expo/vector-icons` library run just as smoothly as other tests.

### Actual Behavior
Tests using the `@expo/vector-icons` library throw the following error:

```bash
$ jest
 FAIL  ./demo-bug-vector-icons.spec.ts
  ● Test suite failed to run

    /Users/gilliamf/Projects/ts-jest-import-bug-demo/node_modules/@expo/vector-icons/build/AntDesign.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import createIconSet from './createIconSet';
                                                                                                    ^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
```

### Reproducible Demo
A very minimal demo reproducing the issue can be found [right here](https://github.com/Gi11i4m/ts-jest-import-bug-demo).

### Combined issue
This issue also happens with `expo-localization`. A combined issue for both of these can be found on the expo GitHub [right here](https://github.com/expo/expo/issues/5296).

**Comment by byCedric** [comment]
You are missing a lot of Expo settings in Jest. Check out the [general documentation here](https://docs.expo.io/versions/latest/guides/testing-with-jest/) and some [additional specific documentation here](https://github.com/expo/expo/tree/master/packages/jest-expo).
