### ISSUE TITLE
Cannot load any fonts

### ISSUE THREAD

**Issue by milesper** [expo/vector-icons#106]
Upon upgrading to Expo 34, I get the message 

> fontFamily "FontAwesome" is not a system font and has not been loaded through Font.loadAsync.

for using FontAwesome, and similarly for Ionicons and FontAwesome5 (presumably all). I have tried manually loading the fonts in App.js, but it doesn't have an effect. I have updated expo-font and recreated node_modules and package-lock again to no effect.

**Comment by jmmendivil** [comment]
Update `babel-preset-expo` to `^5.2.0` and [preload FontAwesome](https://docs.expo.io/versions/v34.0.0/guides/preloading-and-caching-assets/)

**Comment by halfsoft** [comment]
Can you check your app.json and see if your "sdkVersion" is correct ("34.0.0")
I updated my project and I had forgotten to update the app.json which caused FontAwesome not to work.

**Comment by GuillaumeSarfati** [comment]
Hello I experienced the same issue, i remove my node_modules/yarn.lock and nothing solved my error like explained in the other issues. 

I think you need to upgrade to expo 34.0.4 and expo-font 6.0.1

my mistake was iIused Ionicons.font to load the font and not the full path, in my case finally it was just a lower/upper case problem the font required is Ionicons but Ionicons.font has ionicons key in lowercase........ ;)

my code before

```js
const fonts = [
  Ionicons.font,
];
```

and i update by this

```js
const fonts = [
  { Ionicons: Ionicons.font.ionicons },
];
```

after you can just use the expo example font loading fn

```js
cacheFonts(fonts) {
    return fonts.map(font => {
      return Font.loadAsync(font)
    });
  }
```

maybe it's can help someone ;)

**Comment by brentvatne** [comment]
indeed if you use the font name manually via fontFamily as "Ionicons" rather than "ionicons" then this issue will arise

**Comment by milesper** [comment]
Turns out what fixed my issue was making sure everything was updated, then deleting the Expo client app on the simulator I was using.

**Comment by AamuLumi** [comment]
I found a bug in expo installation. See this issue : https://github.com/expo/expo/issues/5507
