### ISSUE TITLE
Missing LICENSE.md

### ISSUE THREAD

**Issue by wscourge** [expo/vector-icons#108]
Please add LICENSE.md file to this repository, so people (like myself) can acknowledge it in their projects.

**Comment by amandeepmittal** [comment]
This library is wrapper over [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons), so I guess it follows the same license from the vector icons one, which is MIT.

**Comment by brentvatne** [comment]
we had the license set in package.json as MIT already but i went ahead and added a LICENSE file as well to be thorough https://github.com/expo/vector-icons/blob/master/LICENSE
