### ISSUE TITLE
Chinese Characters Show instead of Menu Icon

### ISSUE THREAD

**Issue by Nafeelrasheed** [expo/vector-icons#110]
-Hello Everyone,
 I am Using Expo i Just update Sdk 32 to 35.
I am using React-Native-Elements Header when i get apk it show chinese Letter but on Runtime Expo it Show me Menu.
Kindly Help this.
Thanks In Advance
when 
![Screenshot_20191008-122940_nerp360](https://user-images.githubusercontent.com/35622317/66471425-215c1480-ea40-11e9-9c50-5bc6f8122695.jpg)

**Comment by cruzach** [comment]
what version of `@expo/vector-icons` are you using? can you provide a reproducible demo?

**Comment by Nafeelrasheed** [comment]
Sorry For Late Reply i am using @expo/vector-icons: 10.0.6

**Comment by brentvatne** [comment]
as @cruzach said please provide a reproducible example, thanks!

**Comment by mufaddalhamidofficial** [comment]
@Nafeelrasheed  did you solved the problem if yes then how

**Comment by brentvatne** [comment]
if you see this you may have multiple versions of expo-font in your project and you are probably using yarn instead of npm. delete your node_modules and npm-package.lock file, then run npm install again.
