### ISSUE TITLE
Latest react-native-vector-icons & Fontisto Font Bundle

### ISSUE THREAD

**Issue by WrathChaos** [expo/vector-icons#112]
Is that possible to upgrade the version with latest `react-native-vector-icon` with **Fontisto** Font Bundle?

**Comment by clu7ch3r** [comment]
@WrathChaos I have the latest version of `react-native-vector-icon` with fontisto but for some reason, the project tries to find fontisto from `@expo/vector-icons`. How would I import `@expo/vector-icons` after forking the repository and modifying it in a pr?

**Comment by WrathChaos** [comment]
You can either import it with a local library or publish it with npm

**Comment by clu7ch3r** [comment]
I'm not sure what to modify. This repo has a few font directory references. Best to wait for expo to add fontisto to their next update unless someone else has a workaround for expo + fontisto.

**Comment by WrathChaos** [comment]
I will work on it this weekend

**Comment by Iamt-chadwick** [comment]
Hello @WrathChaos . I seem to be having the same issue with Fonisto not been found. Is there any work-around for this? Thanks

**Comment by WrathChaos** [comment]
Hello @Iamt-chadwick, 
Unfortunately, I could not spend time to explore expo's vector-icons library. It should have been easy to add a new bundle but I could not find a very easy way.

**Comment by Iamt-chadwick** [comment]
Alright. Thanks a lot.

**Comment by ziedjebali** [comment]
Any news with regards to this?

**Comment by Monty1337** [comment]
I have the same problem, any update?
I cant use NativeBase with Expo right now because of this issue.

**Comment by zacviandier** [comment]
I came to that issue for the same reason @Monty1337 , I can't use NativeBase with Expo for now with the last version. I downgraded NativeBase to 2.13.8.

**Comment by dernster** [comment]
I'm experiencing the same issue. Had to downgrade to NativeBase 2.13.8 but it has some warnings about deprecated lifecycle methods....

**Comment by tsmuse** [comment]
I also just ran into this issue trying to use NativeBase. Any word on a fix for this?

**Comment by nadernt** [comment]
I have the same issue. My App shows red crash screen. Any change to be fixed soon?

**Comment by singamnv** [comment]
native-base not working for me either. 

I keep getting a 
Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules/native-base/dist/src/basic/IconNB.js"

I've installed expo-fonts like 5 different methods. No avail. Only happens when I try to import native-base into my app.

**Comment by diegolaciar** [comment]
Same here:

`Could not resolve "@expo/vector-icons/Fontisto" in file /Users/***/workspace/***********/node_modules/native-base/dist/src/basic/IconNB.js.
Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules/native-base/dist/src/basic/IconNB.js"
Failed building JavaScript bundle.`

**Comment by ariyas** [comment]
same here, got this issue when trying to run a react native project

Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules\native-base\dist\src\basic\IconNB.js"

undefined Unable to resolve module `@expo/vector-icons/Fontisto` from `node_modules\native-base\dist\src\basic\IconNB.js`: @expo/vector-icons/Fontisto could not be found within the project.

**Comment by nadernt** [comment]
I downgraded to version 2.13.7 now I can continue development but defiantly the latest version is broken and shows the  Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules\native-base\dist\src\basic\IconNB.js".  I tried to give the absolute path to IconNB.js but it is not working too.

**Comment by r-0-0-t** [comment]
I downgraded the version to 2.13.7 but still getting the issue.

>  Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules\native-base\dist\src\basic\IconNB.js". 
any workarounds regards to this?

**Comment by r-0-0-t** [comment]
I changed my **babel.config.js** into
```js
module.exports = function(api) {
    api.cache(true);
    return {
        presets: ["module:metro-react-native-babel-preset"]
    };
```

and voila, everything seemed to working again

**Comment by ntbosscher** [comment]
> I downgraded to version 2.13.7 now I can continue development but defiantly the latest version is broken and shows the Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules\native-base\dist\src\basic\IconNB.js". I tried to give the absolute path to IconNB.js but it is not working too.

It looks like native-base@2.13.8 is the last working version

**Comment by amar1n** [comment]
@ntbosscher, the problem remains with version 2.13.8

**Comment by ntbosscher** [comment]
> @ntbosscher, the problem remains with version 2.13.8

hmm, that's odd b/c mine breaks with 2.13.9, but not with 2.13.8. I'm getting the same exception message as others in this ticket.

Exception message
```
Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules/native-base/dist/src/basic/IconNB.js" Failed building JavaScript bundle
```

This is an excerpt from my yarn.lock file
```
native-base@2.13.8:
  version "2.13.8"
  resolved "https://registry.yarnpkg.com/native-base/-/native-base-2.13.8.tgz#817dfaf74ec63cd17f48991fab452fdc75103db9"
  integrity sha512-47Wm7bjH5Dc99gBUeVvsURyADU97aiLMLPGX4ewPgR9kW47TD9slS/Y5vGMToBgz1bsku9anXgN2T1rpdQbpFA==
```

**Comment by amar1n** [comment]
Every works fine with native-base: 2.13.7, 2.13.8

The problem appears in version ^2.13.8 and remains until 2.13.12

Unable to resolve module @expo/vector-icons/Fontisto from .../node_modules/native-base/dist/src/basic/IconNB.js: Module @expo/vector-icons/Fontisto does not exist in the Haste module map

**Comment by amar1n** [comment]
In short, what you need to install is the exact 2.13.8 version

`npm i --save-exact native-base@2.13.8`

**Comment by selmi-karim** [comment]
any updates?

**Comment by timosur** [comment]
works for me @amar1n  :-) thanks!

**Comment by MuhweziDeo** [comment]
thansk @amar1n  this also worked for me

**Comment by rrust** [comment]
Updating @expo/vector-icons according to the latest native-base package would be great, since babel-preset-expo aliases react-native-vector-icons to @expo/vector-icons

```  if (hasModule('@expo/vector-icons')) {
    aliases['react-native-vector-icons'] = '@expo/vector-icons';
  }```

so if a library depends on a newer version of react-native-vector-icons then @expo/vector-icons does we're getting that "Unable to resolve" error...

**Comment by Monty1337** [comment]
I currently see this as a workaround, but should definitely be fixed.

**Comment by rrust** [comment]
Just to let everyone know....

To work around this issue i simply created a yarn postinstall hook in my package.json which copies an existing Font*.js wrapper file from @expo/vector-icons

 ```
"scripts": {
    "start": "expo start",
    "postinstall": "cp node_modules/@expo/vector-icons/FontAwesome.js node_modules/@expo/vector-icons/Fontisto.js"
  }
```

obviously this is to be removed once @expo/vector-icons is updated...

**Comment by joshg2k** [comment]
Commenting here to show my support for resolving this issue.

**Comment by SeanRenet** [comment]
I literally just duplicated Ionicons into a new file called Fontisto.js. That took away the error.  Anyone have a real fix yet?

**Comment by webbudesign** [comment]
I had the same problem and solved it after install v2.13.8

**Comment by afrojuju1** [comment]
I am having this issue with version 2.13.8

**Comment by YeisonGomez** [comment]
It works for me, however, the icons in the app no ​​longer work

**Comment by raffaeu** [comment]
The bug is still there, I had version 2.13.12 of native-base and went back to 2.13.8
Come'n guys or you fix it or you pass the repo to someone else, this is a basic dependency for native-base

**Comment by cruzach** [comment]
This should be resolved by https://github.com/expo/vector-icons/pull/126

**Comment by avinaash-sharma** [comment]
https://github.com/oblador/react-native-vector-icons/issues/1031

this worked for me..

**Comment by Jerry-devblog** [comment]
Not working with react-native-elements tho

**Comment by adarshkhatri** [comment]
same problem here

**Comment by tonyea** [comment]
It's working fine on 2.13.12 and expo ^38.0.0
