### ISSUE TITLE
IE11 issue: Permission must be Installable.

### ISSUE THREAD

**Issue by d4rky-pl** [expo/vector-icons#118]
The TTF files do not have Installable flag, causing them to not load on IE11 properly.

This might be an upstream issue so I reported this as Templarian/MaterialDesign-Webfont#60 but since this repository keeps its own copy of the file, I'm reporting this in both places

**Comment by d4rky-pl** [comment]
The issue has been fixed upstream but the webfont has to be updated in this repository as well

**Comment by brentvatne** [comment]
hey @d4rky-pl! i have updated to the latest version of react-native-vector-icons, i'm not sure if that includes a fix or not.

if something else needs to be done can you open a pr to this repo to fix it?
