### ISSUE TITLE
Problem with @expo/vector-icons/Fontisno

### ISSUE THREAD

**Issue by Silqunz** [expo/vector-icons#119]
How to solve this problem: 
Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules/react-native-dynamic-vector-icons/lib/components/Icon.tsx"
???

**Comment by 28harishkumar** [comment]
Duplicate [https://github.com/expo/vector-icons/issues/112](https://github.com/expo/vector-icons/issues/112)

**Comment by Rafay3198** [comment]
Same problem 

Unable to resolve "@expo/vector-icons/Fontisto" from "node_modules\native-base\dist\src\basic\IconNB.js"

**Comment by AdamSalma** [comment]
Same issue as well

**Comment by AdamSalma** [comment]
As mentioned in #112:

`npm i --save-exact native-base@2.13.8`

**Comment by ahuacate15** [comment]
> As mentioned in #112:
> 
> `npm i --save-exact native-base@2.13.8`

thanks, work for me!

**Comment by mikahJay** [comment]
Thanks - works for me as well!

**Comment by dharmikvyas** [comment]
To solve it
first step to downgrade Native-Base to 2.13.8
`npm i --save-exact native-base@2.13.8
`than reload and you will get another error 
_invariant violation module appregistry is not a registered callable module_
so use following command to solve it.
`npm start --reset-cache`

**Comment by givenm** [comment]
> To solve it
> first step to downgrade Native-Base to 2.13.8
> `npm i --save-exact native-base@2.13.8 `than reload and you will get another error
> _invariant violation module appregistry is not a registered callable module_
> so use following command to solve it.
> `npm start --reset-cache`

That helped. Thanks

**Comment by YeisonGomez** [comment]
It works for me, however, the icons in the app no ​​longer work

**Comment by dharmikvyas** [comment]
In expo no need to install vector icons, still try to install vector icons
and run npm install command.

**Comment by iamjonbradley** [comment]
I am still having this issue right now.

This is my entire package.json
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.0",
    "expo": "~37.0.3",
    "expo-font": "~8.1.0",
    "native-base": "^2.13.8",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}
`

**Comment by krys-dev** [comment]
> As mentioned in #112:
> 
> `npm i --save-exact native-base@2.13.8`

Worked for me ! thanks

**Comment by dharmikvyas** [comment]
> I am still having this issue right now.
> 
> This is my entire package.json
> `{ "main": "node_modules/expo/AppEntry.js", "scripts": { "start": "expo start", "android": "expo start --android", "ios": "expo start --ios", "web": "expo start --web", "eject": "expo eject" }, "dependencies": { "@expo/vector-icons": "^10.0.0", "expo": "~37.0.3", "expo-font": "~8.1.0", "native-base": "^2.13.8", "react": "~16.9.0", "react-dom": "~16.9.0", "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz", "react-native-web": "~0.11.7" }, "devDependencies": { "@babel/core": "^7.8.6", "babel-preset-expo": "~8.1.0" }, "private": true }`

have you tried `npm start --reset-cache` ? and what issue you are getting? please post your error.

**Comment by brentvatne** [comment]
we added this font in `@expo/vector-icons@10.1.0` - install it and you will have it now! it's also listed on https://expo.github.io/vector-icons/

**Comment by hansbala** [comment]
> To solve it
> first step to downgrade Native-Base to 2.13.8
> `npm i --save-exact native-base@2.13.8 `than reload and you will get another error
> _invariant violation module appregistry is not a registered callable module_
> so use following command to solve it.
> `npm start --reset-cache`

Nice

**Comment by jlpaz** [comment]
I've just tried this command but it doesn't work for me.

> As mentioned in #112:
> 
> `npm i --save-exact native-base@2.13.8`

**Comment by hansbala** [comment]
> I've just tried this command but it doesn't work for me.
> 
> > As mentioned in #112:
> > `npm i --save-exact native-base@2.13.8`

Clear your cache and also run
`expo start -c` to clear your packaging cache

**Comment by jlpaz** [comment]
> > I've just tried this command but it doesn't work for me.
> > > As mentioned in #112:
> > > `npm i --save-exact native-base@2.13.8`
> 
> Clear your cache and also run
> `expo start -c` to clear your packaging cache

I just realized I was working with another version (native-base@2.13.12) so maybe that's the problem and I should downgrade Native-Base to 2.13.8

**Comment by atulchavan10000** [comment]
> we added this font in `@expo/vector-icons@10.1.0` - install it and you will have it now! it's also listed on https://expo.github.io/vector-icons/

this fixed my problem. Thanks

**Comment by brentvatne** [comment]
we show the corresponding version in the header of https://icons.expo.fyi/ now so hopefully that will help!

**Comment by adarshkhatri** [comment]
`expo install` fixed for me.
