### ISSUE TITLE
Website - Icons not fully visible

### ISSUE THREAD

**Issue by glenngijsberts** [expo/vector-icons#120]
Somehow the icons are not fully visible in Chrome (80.0.3987.87). Safari looks good tho.

![Schermafbeelding 2020-02-12 om 10 41 21](https://user-images.githubusercontent.com/14276144/74322514-537dda00-4d84-11ea-8232-e330c21f79f3.png)

**Comment by brentvatne** [comment]
hello! this was an intermittent issue that we resolved for a while ago and forgot to close this issue. thanks for reporting!
