### ISSUE TITLE
Ionicons v5

### ISSUE THREAD

**Issue by tyre** [expo/vector-icons#123]
What would be the process for supporting an updated version of Ionicons? Is it as simple as copying over their glyphs and adding a mapping?

**Comment by nandorojo** [comment]
I was about to post the same issue. Thanks!

**Comment by nandorojo** [comment]
I'm happy to help PR this if someone could point me in the right direction.

**Comment by brentvatne** [comment]
we use the latest version that's used in react-native-vector-icons, which is v4.2.4 ([see here](https://github.com/oblador/react-native-vector-icons#bundled-icon-sets)).

if you update it in that repo we can also update it here but it would be a major version bump

**Comment by nandorojo** [comment]
Got it, thanks! Linking to https://github.com/oblador/react-native-vector-icons/issues/1128

**Comment by RealDyllon** [comment]
Ionicons v5 is now present in: [oblador/react-native-vector-icons](https://github.com/oblador/react-native-vector-icons)

Any timeframe for when we could see them in @expo/vector-icons ?

**Comment by brentvatne** [comment]
updated to react-native-vector-icons@7.1.0 in @expo/vector-icons@12.0.0, which will be part of sdk 40 ([now available in beta](https://blog.expo.io/expo-sdk-40-beta-is-now-available-2e98264f66b2?source=collection_home---6------0-----------------------)). you should be able to install it on older sdk versions to if you explicitly specify that version
