### ISSUE TITLE
Error: Unable to resolve module `./fonts/Ionicons.ttf

### ISSUE THREAD

**Issue by bm-software** [expo/vector-icons#13]
I've a project create with react-native-cli and I've installed native-base library for UI elements.
native-base star asking me to install @expo/vector-icons to work:

> error: bundling failed: "Unable to resolve module `@expo/vector-icons/Ionicons` from `C:\\Code\\ReactNativeProjects\\CaliUp\\node_modules\\native-base\\dist\\src\\basic\\IconNB.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`."

After I've installe the expo package the app still doesn't work, giving me the following error:

> error: bundling failed: "Unable to resolve module `./fonts/Ionicons.ttf` from `C:\\Code\\ReactNativeProjects\\CaliUp\\node_modules\\@expo\\vector-icons\\Ionicons.js`: could not resolve `C:\\Code\\ReactNativeProjects\\CaliUp\\node_modules\\@expo\\vector-icons\\fonts\\Ionicons.ttf' as a folder: it did not contain a package, nor an index file"

This is my package.json file:

This is my package-json:

     {
       "name": "CaliUp",
       "version": "0.0.1",
       "private": true,
       "scripts": {
         "start": "node node_modules/react-native/local-cli/cli.js start",
         "test": "jest"
       },
       "dependencies": {
         "@expo/vector-icons": "^5.0.0",
         "native-base": "^2.2.1",
         "react": "16.0.0-alpha.12",
         "react-native": "0.46.4",
         "react-native-vector-icons": "4.1.1",
         "react-navigation": "^1.0.0-beta.11"
       },
       "devDependencies": {
         "babel-jest": "20.0.3",
         "babel-preset-react-native": "2.1.0",
         "jest": "20.0.4",
         "react-test-renderer": "16.0.0-alpha.12"
       },
       "jest": {
         "preset": "react-native"
       }
     }

How can I solve that?

**Comment by dikaiosune** [comment]
Hi! It seems like you might have used the NativeBase steps for setup with Create React Native App, which comes with these icon files by default. If not, then make sure to follow the non-CRNA instructions on their README and report issues to them if you're still having problems. Thanks!
