### ISSUE TITLE
Failed prop type: Invalid prop `name` of value `calendar-month` supplied to `Icon`

### ISSUE THREAD

**Issue by Luckygirlllll** [expo/vector-icons#130]
I'm getting an error, when trying to use `calendar-month` icon from MaterialCommunityIcons  

> Failed prop type: Invalid prop `name` of value `calendar-month` supplied to `Icon`

`  <MaterialCommunityIcons  name="calendar-month" size={25} color="white"/>`

 "@expo/vector-icons": "^10.1.0"

All other icons work, for example` calendar-blank`.

**Comment by amandeepmittal** [comment]
Hi @Luckygirlllll,

Can you please check that the icon `calendar-month` exists in Expo vector icons directory [here](https://icons.expo.fyi/)?

**Comment by Luckygirlllll** [comment]
@amandeepmittal it doesn't exist in this new directory. Expo deleted old icons in the new version?

**Comment by amandeepmittal** [comment]
I just checked it does exist there in [react-native-vector-icons](https://oblador.github.io/react-native-vector-icons/) so it should be there in Expo too. 

I will cc @brentvatne here. He is the best person to solve this issue.

**Comment by brentvatne** [comment]
hello @Luckygirlllll! i published 10.2.0 which pulls in glyphs from the latest version of react-native-vector-icons and `calendar-month` is there!

direct link: https://icons.expo.fyi/MaterialCommunityIcons/calendar-month
