### ISSUE TITLE
Using with expo-electron resolves font from relative path

### ISSUE THREAD

**Issue by wagnerpaz** [expo/vector-icons#132]
Using @expo/vector-icons with expo-electron causes the fonts to be resolved from relative path.
For example, if I'm at root http://localhost:9080/ it resolves to http://localhost:9080/fonts/FontAwesome--Fonts.ttf and that's ok, insted if I'm on http://localhost:9080/path/ it resolves to http://localhost:9080/path/fonts/FontAwesome--Fonts.ttf causing a 404 error.

**Comment by brentvatne** [comment]
electron support is pretty early/alpha and not something we actively work on at the moment, as we're focused on ios/android/web. i'll close this because it's not something we would fix in this library anyhow, but would have to be part of the electron package instead
