### ISSUE TITLE
Some MaterialCommunityIcons is blank in @expo/vector-icons@10.2.0

### ISSUE THREAD

**Issue by imwilliamxy** [expo/vector-icons#135]
I'm using expo to build my app.
After upgrade to SDK 37, some icon is blank in @expo/vector-icons@10.2.0
Following is empty i found:
MaterialCommunityIcons/credit-card
MaterialCommunityIcons/credit-card-multiple
MaterialCommunityIcons/credit-card-off
MaterialCommunityIcons/credit-card-plus
MaterialCommunityIcons/credit-card-scan
MaterialCommunityIcons/credit-card-settings

Also can check these icons on  https://icons.expo.fyi/

**Comment by jonathanstiansen** [comment]
I've also found MaterialCommunityIcons/gas-station-outline to be blank, which is listed as available on the site: https://icons.expo.fyi/MaterialCommunityIcons/gas-station-outline

**Comment by jonathanstiansen** [comment]
So we fixed this by doing a expo install expo/vector-icons to update the package and it worked.
