### ISSUE TITLE
Icons centered ?

### ISSUE THREAD

**Issue by martinezguillaume** [expo/vector-icons#14]
Yo ! I'm using expo and this lib to render icon component and I find that the icons are not vertically centered. Maybe I'm using it wrong, but even if I render just the Icon component and put his background color to see better, the icon is clearly not centered.

![image](https://user-images.githubusercontent.com/17292331/28417557-d39f5e52-6d58-11e7-84a1-cac2731405b6.png)

```js
import { Ionicon } from '@expo/vector-icons'

<Ionicon
  color='white'
  name='close'
  style={ { backgroundColor: 'red' } }
/>
```

I tried to put `alignItems: 'center'` and `justifyContent: 'center'` to `style` without success...

If I put `paddingTop: 2` to `style`, the icon is centered

![image](https://user-images.githubusercontent.com/17292331/28417903-1876d2a2-6d5a-11e7-9057-dbaa50e29ab4.png)

**Comment by dikaiosune** [comment]
Hi! As the README states, this is just a wrapper around oblador/react-native-vector-icons -- unless you're having issues integrating the wrapper into your project, I'd recommend opening issues on that repository. Thanks!
