### ISSUE TITLE
Icons list update needed

### ISSUE THREAD

**Issue by PoulsQ** [expo/vector-icons#145]
Is it possible to update the list of icons available to match what's available on `@oblador/react-native-vector-icons` because we have a lot of icons missing here, like `MaterialIcons/biotech` and it would be great to have an update in the expo package to be able to use those wonderful icons !

(actually as this package is not up to date, it's a total mess between expo and react-native-vector-icons)

![Capture d’écran 2020-10-14 à 18 38 18](https://user-images.githubusercontent.com/4129609/96019169-751bed80-0e4c-11eb-9e36-e055ed7b9e59.png)

**Comment by brentvatne** [comment]
updated to react-native-vector-icons@7.1.0 in @expo/vector-icons 12.0.0, which will be part of sdk 40 ([now available in beta](https://blog.expo.io/expo-sdk-40-beta-is-now-available-2e98264f66b2?source=collection_home---6------0-----------------------)). you should be able to install it on older sdk versions to if you explicitly specify that version

**Comment by PoulsQ** [comment]
Thank you @brentvatne !
But just specifying `@expo/vector-icons@12.0.0` in my `package.json` throw me that error:

```
error: Error: Unable to resolve module `./toolbar-android` from `node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/lib/create-icon-set.js`: 

None of these files exist:
  * node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/lib/toolbar-android(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/lib/toolbar-android/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/myuser/Projets/JS/myproject/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/myuser/Projets/JS/myproject/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/myuser/Projets/JS/myproject/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/myuser/Projets/JS/myproject/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/myuser/Projets/JS/myproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/myuser/Projets/JS/myproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/myuser/Projets/JS/myproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/myuser/Projets/JS/myproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

Should I install another package to make this work?

**Comment by brentvatne** [comment]
@PoulsQ what code are you using that results in that error?

**Comment by brentvatne** [comment]
there is no mention of `toolbar-android` in https://github.com/expo/vector-icons/blob/master/build/vendor/react-native-vector-icons/lib/create-icon-set.js

so, i imagine there is some caching issue on your end. try running `expo start -c`

**Comment by PoulsQ** [comment]
This was due to an interaction with the lib `react-native-vector-icons`...
I removed it and now I don't have any problems...

Thank you a lot for your help!
