### ISSUE TITLE
How to remove padding from vector icons in Expo

### ISSUE THREAD

**Issue by kaushikdas0** [expo/vector-icons#15]
If i use the vector icons in Expo i see lot of padding space is added around the icon by default. [Green color in the screenshot attached, thats the padding for a 15px icon]. Is there a way to remove that extra padding? Tried manual overriding of padding and margin but didn't worked. Sample code for the screenshot provided:
`<Entypo name="triangle-down" size={15} color="#9013FE" style={{
                                    backgroundColor: 'green',
                                    }}/>`

![7ywqb](https://user-images.githubusercontent.com/13030179/28773278-6e1419b2-761b-11e7-9110-0ec64ccd1f06.jpg)

**Comment by dikaiosune** [comment]
Hi! As the README states, this is just a wrapper around https://github.com/oblador/react-native-vector-icons --  unless you're having issues integrating the wrapper into your project, I'd recommend opening issues on that repository. Thanks!
