### ISSUE TITLE
Feather Music Icon rendering wrong

### ISSUE THREAD

**Issue by jeremiasjutz** [expo/vector-icons#150]
Since the version 12 Update, the Music Icon from the Feather icon Library is rendering wrong. (2 white spots in the circles)
![music](https://user-images.githubusercontent.com/31439896/101736184-4b391d00-3ac3-11eb-9d8c-a6b2f9952157.png)

**Comment by brentvatne** [comment]
this library largely just wraps react-native-vector-icons to make it use expo-font, and we stay up to date with what they are using. the best way to fix this is to open a pr to react-native-vector-icons to fix it there. this appears to be in the icon font file itself, the same issue happens on web

**Comment by jeremiasjutz** [comment]
https://github.com/oblador/react-native-vector-icons/issues/1351
