### ISSUE TITLE
Unrecognized font family 'ionicons' - Error in Expo Client on iOS

### ISSUE THREAD

**Issue by dderrickmatheww** [expo/vector-icons#152]
**Hello Expo team,**

I've been searching the internet looking for a solution to this issue but I haven't had much success. I recently updated to expo-cli v4.0.13 and updated the expo sdk to 40.0.0. Since the update I'm now seeing an error when I open my application on iOS via the expo client: **"Unrecognized font family 'ionicons'"** along with many other vector-icon names.

I've check the @expo/vector-icons directory here: **[https://icons.expo.fyi/](url)** and was able to find many of the icons I'm using. All of my icons now are question marks and I can't seem to get them back. I've removed my node_modules, cleared npm cache, removed .expo/ and the package.json, uninstalled expo-cli. I've tried configuring the settings for the metro in the .config.js file. I've tried loading them with expo-font. Nothing seems to work. The application runs fine without the icons but obviously I would like them to render correctly.  Could you guys help me out?

![IMG_0446](https://user-images.githubusercontent.com/45571130/102442476-7c00e100-3ff2-11eb-8ea1-06458198c945.jpg)
![IMG_0441](https://user-images.githubusercontent.com/45571130/102442486-802cfe80-3ff2-11eb-9932-d9eea828465a.jpg)
![IMG_0443](https://user-images.githubusercontent.com/45571130/102442495-828f5880-3ff2-11eb-87d8-acf985cba7ba.jpg)
![IMG_0442](https://user-images.githubusercontent.com/45571130/102442499-84591c00-3ff2-11eb-9d6f-602709a7f00e.jpg)
![IMG_0444](https://user-images.githubusercontent.com/45571130/102442505-858a4900-3ff2-11eb-821d-8dcec7056663.jpg)
![IMG_0445](https://user-images.githubusercontent.com/45571130/102442509-86bb7600-3ff2-11eb-9ca0-149b4d20e4ca.jpg)

**Comment by gasolin** [comment]
met the same issue on expo sdk 40

works fine in expo 39

**Comment by dderrickmatheww** [comment]
@gasolin If I revert to SDK 39, do you know if I have to revert my expo-cli to a specific version as well?

**Comment by giuvincenzi** [comment]
I've had the same problem.
My problem was a configuration in the "metro.config.js" file.

```
module.exports = {
  resolver: {
    sourceExts: ['jsx', 'js', 'ts', 'tsx'], // remove this
  },
};
```

After I removed the `sourceExts` property the problem is fixed.

**Comment by gasolin** [comment]
Test snack / expo init blank project and `@expo/vector-icons` works fine.

I use the metro.config.js config suggest in  https://github.com/kristerkari/react-native-svg-transformer/blob/master/README.md#for-react-native-v057-or-newer--expo-sdk-v3100-or-newer

might related

**Comment by gasolin** [comment]
@dderrickmatheww can always used the latest expo-cli for supported SDK versions

**Comment by gasolin** [comment]
Change the sourceExts to the same list as app.json fixed this issue

https://github.com/kristerkari/react-native-svg-transformer/issues/116#issue-773455991

**Comment by brentvatne** [comment]
if you're having this issue, you may have a custom metro config that doesn't modify sourceExts properly or somehow clobbers it. see https://docs.expo.io/guides/customizing-metro/ for a guide on how you should customize metro using @expo/metro-config
