### ISSUE TITLE
Icon names types are not exported

### ISSUE THREAD

**Issue by VictorAssis** [expo/vector-icons#153]
fca0e34f827bc172012a0dd58a384d542d7dee67 turned possible to autocomplete the icons names, but is not possible to reference in a wrapper component (without copy and paste the names manually) because the names are not a separated type.

For example i had this component working in a older version of @expo/vector-icons:
```typescript
import { MaterialIcons } from '@expo/vector-icons';

interface Props {
  icon: string,
  label: string,
  color: string
}

const CustomDrawerItem = ({ icon, label, color }: Props) => (
  <View>
    <MaterialIcons
      name={icon}
      color={color}
    />
    <Text>{label}</Text>
  </View>
}
```

In the current version, Typescript present the error `Type 'string' is not assignable to type '"label" | "style" | (...)`.

Is it possible to export the names in a separate type for import as below?

```typescript
import { MaterialIcons, MaterialIconsNames } from '@expo/vector-icons';

interface Props {
  icon: MaterialIconsNames,
  label: string,
  color: string
}

const CustomDrawerItem = ({ icon, label, color }: Props) => (
  <View>
    <MaterialIcons
      name={icon}
      color={color}
    />
    <Text>{label}</Text>
  </View>
}
```

Or is there another solution?

**Comment by de1ay** [comment]
Try this

```typescript
import { MaterialIcons } from '@expo/vector-icons';

type Props = {
  materialIconName: keyof typeof MaterialIcons.glyphMap;
}
```

Result

![Screenshot 2020-12-31 004823](https://user-images.githubusercontent.com/16839849/103382924-ea20ca00-4b01-11eb-814e-85ddf2c9d65c.png)

**Comment by VictorAssis** [comment]
This works fine! Thanks!

**Comment by brentvatne** [comment]
the solution suggested by @de1ay is a common way to do this kind of thing. if someone would like to propose an alternative approach to exposing the icon name prop along with some justification on why it's worth adding the extra surface area to api and documentation, please do!

**Comment by soullivaneuh** [comment]
@brentvatne The approach looks good too me. It should be added on top of the documentation, this is a very useful trick that deserve a better place than a github issue comment. :wink:

**Comment by brentvatne** [comment]
feel free to send a pr for it - that said, extracting types of props on a component is a pretty common thing to do when using react libraries with typescript, so you can use this common pattern:

```
type MaterialIconName = React.ComponentProps<typeof MaterialIcons>['name'];
const iconName: MaterialIconName =  '3d-rotation'
```

example of it in action:

<img width="689" alt="Screen Shot 2021-02-27 at 12 24 32 PM" src="https://user-images.githubusercontent.com/90494/109399301-ebe6ee00-78f6-11eb-9655-e5cc3c3d4013.png">

**Comment by JereLima** [comment]
import React from "react";
import { View } from "react-native";
import {
  AntDesign,
  Entypo,
  EvilIcons,
  Feather,
  FontAwesome,
  FontAwesome5,
  Fontisto,
  Foundation,
  Ionicons,
  MaterialCommunityIcons,
  MaterialIcons,
  SimpleLineIcons,
  Zocial,
} from "@expo/vector-icons";

type IconNameMap = {
  AntDesign: keyof typeof AntDesign.glyphMap;
  Entypo: keyof typeof Entypo.glyphMap;
  EvilIcons: keyof typeof EvilIcons.glyphMap;
  Feather: keyof typeof Feather.glyphMap;
  FontAwesome: keyof typeof FontAwesome.glyphMap;
  FontAwesome5: keyof typeof FontAwesome5.glyphMap;
  Fontisto: keyof typeof Fontisto.glyphMap;
  Foundation: keyof typeof Foundation.glyphMap;
  Ionicons: keyof typeof Ionicons.glyphMap;
  MaterialCommunityIcons: keyof typeof MaterialCommunityIcons.glyphMap;
  MaterialIcons: keyof typeof MaterialIcons.glyphMap;
  SimpleLineIcons: keyof typeof SimpleLineIcons.glyphMap;
  Zocial: keyof typeof Zocial.glyphMap;
};

type MyIconProps<F extends keyof typeof IconComponentMap> = {
  familyIcon: F;
  iconName: IconNameMap[F];
  size: number;
};

const IconComponentMap = {
  AntDesign: AntDesign,
  Entypo: Entypo,
  EvilIcons: EvilIcons,
  Feather: Feather,
  FontAwesome: FontAwesome,
  FontAwesome5: FontAwesome5,
  Fontisto: Fontisto,
  Foundation: Foundation,
  Ionicons: Ionicons,
  MaterialCommunityIcons: MaterialCommunityIcons,
  MaterialIcons: MaterialIcons,
  SimpleLineIcons: SimpleLineIcons,
  Zocial: Zocial,
};

const MyIcon = <F extends keyof typeof IconComponentMap>({
  familyIcon,
  iconName,
  size = 32,
}: MyIconProps<F>) => {
  const IconComponent: JSX.ElementType =
    IconComponentMap[familyIcon] || Feather;

  return (
    <View>
      <IconComponent name={iconName} size={size} color="black" />
    </View>
  );
};

export default MyIcon;

**Comment by JereLima** [comment]
`
    import React from "react";
    import { View } from "react-native";
    import {
      AntDesign,
      Entypo,
      EvilIcons,
      Feather,
      FontAwesome,
      FontAwesome5,
      Fontisto,
      Foundation,
      Ionicons,
      MaterialCommunityIcons,
      MaterialIcons,
      SimpleLineIcons,
      Zocial,
    } from "@expo/vector-icons";
    
    type IconNameMap = {
      AntDesign: keyof typeof AntDesign.glyphMap;
      Entypo: keyof typeof Entypo.glyphMap;
      EvilIcons: keyof typeof EvilIcons.glyphMap;
      Feather: keyof typeof Feather.glyphMap;
      FontAwesome: keyof typeof FontAwesome.glyphMap;
      FontAwesome5: keyof typeof FontAwesome5.glyphMap;
      Fontisto: keyof typeof Fontisto.glyphMap;
      Foundation: keyof typeof Foundation.glyphMap;
      Ionicons: keyof typeof Ionicons.glyphMap;
      MaterialCommunityIcons: keyof typeof MaterialCommunityIcons.glyphMap;
      MaterialIcons: keyof typeof MaterialIcons.glyphMap;
      SimpleLineIcons: keyof typeof SimpleLineIcons.glyphMap;
      Zocial: keyof typeof Zocial.glyphMap;
    };
    
    type MyIconProps<F extends keyof typeof IconComponentMap> = {
      familyIcon: F;
      iconName: IconNameMap[F];
      size: number;
    };
    
    const IconComponentMap = {
      AntDesign: AntDesign,
      Entypo: Entypo,
      EvilIcons: EvilIcons,
      Feather: Feather,
      FontAwesome: FontAwesome,
      FontAwesome5: FontAwesome5,
      Fontisto: Fontisto,
      Foundation: Foundation,
      Ionicons: Ionicons,
      MaterialCommunityIcons: MaterialCommunityIcons,
      MaterialIcons: MaterialIcons,
      SimpleLineIcons: SimpleLineIcons,
      Zocial: Zocial,
    };
    
    const MyIcon = <F extends keyof typeof IconComponentMap>({
      familyIcon,
      iconName,
      size = 32,
    }: MyIconProps<F>) => {
      const IconComponent: JSX.ElementType =
        IconComponentMap[familyIcon] || Feather;
    
      return (
        <View>
          <IconComponent name={iconName} size={size} color="black" />
        </View>
      );
    };
    
    export default MyIcon;


`

**Comment by Valli-** [comment]
That solution can slow down the intellisense, https://github.com/microsoft/TypeScript/wiki/Performance#preferring-base-types-over-unions. I was testing it out and took quite big performance issue after a while.
