### ISSUE TITLE
MaterialCommunityIcons coin and coins shows ( ? )

### ISSUE THREAD

**Issue by 3Omar3** [expo/vector-icons#157]
I tried with other icons and it works correctly but these specifically do not.

**package.json:**
"@expo/vector-icons": "^12.0.3",

**Comment by brentvatne** [comment]
press shift+refresh on https://icons.expo.fyi/ to reload the page without cache. if that doesn't work, open up chrome dev tools and delete the service worker and reload again. sorry for the hassle! you will know it's working when you see this version
![Screen Shot 2021-02-25 at 6 59 33 PM](https://user-images.githubusercontent.com/90494/109248933-9cd87600-779b-11eb-8d65-9305e720ff20.png)
