### ISSUE TITLE
Could you add "iOS dismiss bar" icon?

### ISSUE THREAD

**Issue by QiYuNew** [expo/vector-icons#158]
The icon looks like the one in the following post:
The little single-bar with smooth edges
[link](https://stackoverflow.com/questions/58382329/swift-presenting-controller-dismiss-bar-indicator)

Thank you very much!

**Comment by 3Omar3** [comment]
you can do a div or view styled like that and export then as a component

**Comment by QiYuNew** [comment]
> you can do a div or view styled like that and export then as a component

I mean I want that "drag handle" /"bar" like icon

**Comment by brentvatne** [comment]
`<View style={{width: 100, height: 10, borderRadius: 5, backgroundColor: "rgba(255,255,255,0.6)" />` or something like that should be fine. you don't need an icon for this
