### ISSUE TITLE
Impossible to resolve module for RN 0.47

### ISSUE THREAD

**Issue by yolosaucisson** [expo/vector-icons#17]
Hello,

When I want to use the plugin for react native 0.47, I did the react-native link and add the line "apply ..." for the "react-native-vector-icons"
But i have a problem with red screen that the module with MaterialCommunityIcons.ttf is not found, maybe not package nor index file... and in the error message there is "@expo" so i think that it this repo that doesn't work well...

Please help me :(
Sincerely,

**Comment by yolosaucisson** [comment]
Unable to resolve module `./fonts/Ionicons.ttf` from `/home/aurelio/Desktop/mobileProject/node_modules/@expo/vector-icons/Ionicons.js`: could not resolve `/home/aurelio/Desktop/mobileProject/node_modules/@expo/vector-icons/fonts/Ionicons.ttf' as a folder: it did not contain a package, nor an index file

**Comment by maryhowell** [comment]
I am also having this same issue currently.  I can not seem to find anyway around it. Any ideas would be greatly appreciated.

**Comment by chenkaiC4** [comment]
![image](https://user-images.githubusercontent.com/7543145/30409261-8e94fe02-9936-11e7-8104-b3fcad383467.png)

any helper?
```
"@expo/vector-icons": "^5.2.0",
"expo": "^19.0.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-19.0.0.tar.gz",
```

**Comment by maryhowell** [comment]
Hi @chenkaiC4 I had this same problem.  Is your project a CRNA or react-native init.  If you are the later that might be your problem. (or that was our problem).  If you are using react-native init it does not support expo and that is why it is having problems. Let me know if you have any questions about this. Someone from Expo was nice enough to help my team and I though this problem and revert our project to a CRNA, that fixed it.
