### ISSUE TITLE
Feather at-sign icon broken

### ISSUE THREAD

**Issue by weynelucas** [expo/vector-icons#178]
I'm using Feather icons with

```
"@expo/vector-icons": "^12.0.4",
"expo": "^41.0.0"
```

The icons work fine but I realize that `at-sign` icon are broken, like some content was cut (see image bellow)

![image](https://user-images.githubusercontent.com/12589558/123650173-b698d100-d800-11eb-8aba-ba0a256b3096.png)

On `expo/vector-icons` page this icon are listed with the same error:
![image](https://user-images.githubusercontent.com/12589558/123650585-18f1d180-d801-11eb-8db3-d114cd520c2b.png)

Here's the icon on official [Feather Icons page](https://feathericons.com/?query=at-sig) (`v4.28.0`):
![image](https://user-images.githubusercontent.com/12589558/123650750-42126200-d801-11eb-84e5-e17ab46f8842.png)

**Comment by hbiede** [comment]
This seems to have been fixed
