### ISSUE TITLE
Unable to resolve module lodash/isString and etc.

### ISSUE THREAD

**Issue by OverVlad** [expo/vector-icons#18]
When build app have error Unable resolve module 'ladash/isEqual'.
![image](https://user-images.githubusercontent.com/15329933/29583128-bb05a18c-8787-11e7-8df4-4df0c0812c66.png)

This error occurred because in files import file like this 
`import isEqual from 'lodash/isEqual';`
How can I resolve this error?

**Comment by OverVlad** [comment]
#19

**Comment by OverVlad** [comment]
#19

**Comment by brentvatne** [comment]
thanks for the PR!

**Comment by sushil50889** [comment]
I have the same issue. I fixed it by the following --

Re-Install the module by : npm install lodash --save
And run expo by : expo start --clear
Thanks.

**Comment by brentvatne** [comment]
@sushil50889 - maybe you are using an old version of @expo/vector-icons? `lodash/*` is never imported here. `lodash.*` is in some cases, eg: `lodash.omit`, but that is included in package.json: https://github.com/expo/vector-icons/blob/e4a7da71fbfd137cd7a3027ec6d1d7c8dd2ab239/package.json#L43-L50
