### ISSUE TITLE
banckward !!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by samertime92** [expo/vector-icons#198]
keep expo a a professional place please and fix backward icon naming (banckward)

**Comment by mikeallbutt** [comment]
I also found that this issue  https://github.com/Templarian/MaterialDesign/issues/5269 has been fixed but the new icon name does not work here https://icons.expo.fyi/

<img width="341" alt="Screen Shot 2022-03-28 at 11 43 56" src="https://user-images.githubusercontent.com/43966676/160459443-6e67eec0-9aaf-4e65-a99c-4189019d5e0d.png">

**Comment by brentvatne** [comment]
`@expo/vector-icons@13.0.0` bumps to the latest versions of icon libraries used in react-native-vector-icons@9.1.0
