### ISSUE TITLE
Support FontAwesome6

### ISSUE THREAD

**Issue by cyoung43** [expo/vector-icons#201]
Currently I can import FontAwesome5 (`import { FontAwsome5 } from '@expo/vector-icons`). When will Font Awesome 6 be available?

**Comment by gauel** [comment]
Wondering the same thing

**Comment by efstathiosntonas** [comment]
hey folks, there seems to be a fork that supports FontAwesome 6:

install it with: 
`yarn add https://github.com/gauel/vector-icons`

**Comment by jeanengelbrecht02** [comment]
i see that the wrapper now supports https://github.com/oblador/react-native-vector-icons/tree/master/Fonts so we litterly just waiting for this package to update

**Comment by david-j-lee** [comment]
I would like to see FontAwesome6 support as well

**Comment by willrcline** [comment]
Still waiting on this
