### ISSUE TITLE
Loading icon

### ISSUE THREAD

**Issue by mgscreativa** [expo/vector-icons#22]
Hi! I'm using Ionicons from @expo/vector-icons@5.2.0, is there a loading icon? I can't find any here https://github.com/expo/vector-icons/blob/master/vendor/react-native-vector-icons/glyphmaps/Ionicons.json and if I try ion-load-b or ion-load-c I got a nice '?' icon.

**Comment by CapitanRedBeard** [comment]
@mgscreativa Mind closing this issue also with since I think we resolve it with #23 ?
