### ISSUE TITLE
`MaterialCommunityIcons` missing `telegram` icon

### ISSUE THREAD

**Issue by thedoublejay** [expo/vector-icons#220]
With `@expo/vector-icons@13.0.0`, telegram icon is missing on `MaterialCommunityIcons`. It was available on `@expo/vector-icons@12.0.0`

**Comment by hbiede** [comment]
It was removed from the icon set:
https://pictogrammers.com/docs/library/mdi/releases/changelog/#version-6.1.95

**Comment by Simek** [comment]
With updated vendored package version, the icon will be now available in the `MaterialIcons` set.

![Screenshot 2023-12-27 at 12 35 30](https://github.com/expo/vector-icons/assets/719641/6cb40022-30fe-4dd6-b5ab-e281153e3a8a)
