### ISSUE TITLE
typescript error 'Ionicons' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by Kir93** [expo/vector-icons#225]
- version
  - expo : 45
  - react : 17.0.2
  - react-native : 0.68.2

Error Message is
'Ionicons' cannot be used as a JSX component.

  Its instance type 'Component<IconProps<"moon" | "body" | "code" | "link" | "map" | "menu" | "time" | "ellipse" | "filter" | "image" | "stop" | "text" | "search" | "repeat" | "at" | "key" | "alert" | "checkbox" | "document" | ... 3661 more ... | "md-woman-sharp">, {}, any>' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
Type 'import("/Volumes/T7/toy/project/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
Type '{}' is not assignable to type 'ReactNode'. ts(2786)

how can i fix this error?
Any help would be appreciated.

**Comment by miege2k** [comment]
Same issue for me.

**Comment by viniciusreiss** [comment]
Same error here.

**Comment by Kir93** [comment]
@types/react: 18.0.14. type error fixed.
