### ISSUE TITLE
Update IonIcons icons to latest version

### ISSUE THREAD

**Issue by stefan-schweiger** [expo/vector-icons#229]
Just noticed that some IonIcons icons are not available with vector-icons. For example `calendar-clear-outline` or `calendar-number-outline` and `calendar-outline` does not have the current style.

**Comment by mcsky** [comment]
I noticed the same today while trying to use multiple icons available inside the IonIcons font.

**Comment by alichatraei** [comment]
Ok,Thankyou

**Comment by ericpoulinnz** [comment]
I've run into this too. It looks like #266 might resolve this. @brentvatne @Simek is this library still being maintained? The PR I referenced looks to keep this library current.
