### ISSUE TITLE
Put icon in infinite rotation loop

### ISSUE THREAD

**Issue by mgscreativa** [expo/vector-icons#23]
How can I put an icon to infinite rotation loop?

Thanks!

**Comment by CapitanRedBeard** [comment]
You could wrap the `Icon` component in an `Animated.View` and infinitely rotate the `View`.  
Here is a great resource for anything `Animated` related --> http://browniefed.com/react-native-animation-book/API.html

**Comment by mgscreativa** [comment]
Cool, thanks!

**Comment by brentvatne** [comment]
you can use the `Animated.loop` function to this along with the `Animated` API that @CapitanRedBeard mentioned above!
