### ISSUE TITLE
New Twitter (X) icon

### ISSUE THREAD

**Issue by TianMeh** [expo/vector-icons#268]
As we all probably know, twitter has changed it's logo and name.

I noticed in: https://icons.expo.fyi/Index 

That the new twitter logo is not yet available, I believe.

for example: https://fontawesome.com/icons/x-twitter?f=brands&s=solid

Are there any plans to add this icon?

**Comment by hbiede** [comment]
The X logo is included in Font Awesome 6, thus would be solved through #275
