### ISSUE TITLE
Support for FontAwesome v6

### ISSUE THREAD

**Issue by ammar-oker** [expo/vector-icons#273]
# Use Case
With the recent release of FontAwesome v6, which includes an array of new icons and enhancements, it's imperative for developers using expo/vector-icons to have access to this updated set. This becomes especially relevant since @oblador/react-native-vector-icons has already begun supporting FontAwesome v6.

**Comment by hbiede** [comment]
Ported on #275, waiting on maintainer approval

**Comment by kota113** [comment]
What is the current status of this PR? 
I need this to be merged to use FA6.

**Comment by hbiede** [comment]
Based some discussion I had after making #275, it sounds as though Expo does not plan to continue developing this package as a wrapper for `react-native-vector-icons`

**Comment by hotrungnhan** [comment]
many thanks @brentvatne bre

**Comment by hotrungnhan** [comment]
But i have an issue when update to 14.0.0 
ERROR  TypeError: Cannot convert null value to object
