### ISSUE TITLE
Specify size and color in the style of NativeWind

### ISSUE THREAD

**Issue by bdm-k** [expo/vector-icons#277]
Hello,

I'd like to request a new feature.  
It would be very helpful if we could specify the size and color of icons in the style of NativeWind. [NativeWind](https://www.nativewind.dev/) is a React Native library that enables you to style components in the same manner as Tailwind CSS.

Suppose we have the following icon:
```JSX
<SimpleLineIcons name="picture" size={24} color="#1f2937" />
```
Under the proposed NativeWind styling, it would be transformed to:
```JSX
<SimpleLineIcons name="picture" className="text-2xl leading-6 text-gray-800" />
```

As I'm not an expert in NativeWind or this library, I'm not sure if this request falls within the scope of this project. If it doesn't, please feel free to inform me and close this issue.

Thank you for considering this enhancement!

**Comment by tyrauber** [comment]
This is actually possible in Nativewind V4 using `cssInterop`.

```
import { cssInterop } from 'nativewind';
import FontAwesome from '@expo/vector-icons/FontAwesome';

cssInterop(FontAwesome, {
  className: {
    target: "style",
    nativeStyleToProp: { height: true, width: true, size: true},
  },
});

...

<FontAwesome name="info-circle" className="color-black dark:color-white text-4xl" />
```

See this issue here for additional info: https://github.com/marklawlor/nativewind/issues/614

**Comment by onizukanaim** [comment]
We need to wrap each icon with this method, which is a bit confusing.

**Comment by SMUEric1127** [comment]
> We need to wrap each icon with this method, which is a bit confusing.

Hey @onizukanaim and whoever coming to this looking for a global way, just do this once in _layout.tsx and it would be apply globally!

**Comment by redwanul10** [comment]
Just add this in the `index.js` or `_layout.js` file to globally enable CSS for all SVG icons.
```javascript
import Svg from 'react-native-svg';

cssInterop(Svg, {
  className: {
    target: 'style',
    nativeStyleToProp: { height: true, width: true, size: true },
  },
});
```

**Comment by rohankm** [comment]
use this in _layout.tsx

```
import * as Icons from "@expo/vector-icons";
import { cssInterop } from "nativewind";

// Loop through all exported icons from @expo/vector-icons
Object.keys(Icons).forEach((iconKey) => {
  const IconComponent = Icons[iconKey];

  // Apply cssInterop to each icon component dynamically
  if (IconComponent) {
    cssInterop(IconComponent, {
      className: {
        target: "style",
        nativeStyleToProp: { height: true, width: true, size: true },
      },
    });
  }
});
```
