### ISSUE TITLE
Why is the latest version (14.0.0) not published yet?

### ISSUE THREAD

**Issue by outaTiME** [expo/vector-icons#288]
Hello there, 
does anyone know why the latest version is not released yet? 
The "latest" version is still fixed at ^13.0.0.
I tried to use the latest version with the Expo 49 SDK, and it worked perfectly, but I'm afraid to release productively with this dependency.

**Comment by yybawang** [comment]
save expo and vector-icons version,
just install `"@expo/vector-icons": "^14.0.0",` it's worked
