### ISSUE TITLE
Feather not working

### ISSUE THREAD

**Issue by mikailcetinkaya** [expo/vector-icons#30]
Feather icons are not working

Error :

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

Check the render method of `StaticRenderer`.

instantiateReactComponent
    ReactNativeStack-dev.js:1960:75
instantiateChild
    ReactNativeStack-dev.js:2702:86
traverseStackChildrenImpl
    ReactNativeStack-dev.js:2669:215
traverseStackChildrenImpl
    ReactNativeStack-dev.js:2673:101
instantiateChildren
    ReactNativeStack-dev.js:2709:39
_reconcilerInstantiateChildren
    ReactNativeStack-dev.js:2843:121
mountChildren
    ReactNativeStack-dev.js:2865:59
initializeChildren
    ReactNativeStack-dev.js:2940:45
mountComponent
    ReactNativeStack-dev.js:2969:84
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
mountChildren
    ReactNativeStack-dev.js:2871:62
initializeChildren
    ReactNativeStack-dev.js:2940:45
mountComponent
    ReactNativeStack-dev.js:2969:84
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
mountChildren
    ReactNativeStack-dev.js:2871:62
initializeChildren
    ReactNativeStack-dev.js:2940:45
mountComponent
    ReactNativeStack-dev.js:2969:84
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
mountChildren
    ReactNativeStack-dev.js:2871:62
initializeChildren
    ReactNativeStack-dev.js:2940:45
mountComponent
    ReactNativeStack-dev.js:2969:84
mountComponent
    ReactNativeStack-dev.js:1327:53
mountChildren
    ReactNativeStack-dev.js:2871:62
initializeChildren
    ReactNativeStack-dev.js:2940:45
mountComponent
    ReactNativeStack-dev.js:2969:84
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
mountChildren
    ReactNativeStack-dev.js:2871:62
initializeChildren
    ReactNativeStack-dev.js:2940:45
mountComponent
    ReactNativeStack-dev.js:2969:84
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
mountChildren
    ReactNativeStack-dev.js:2871:62
initializeChildren
    ReactNativeStack-dev.js:2940:45
mountComponent
    ReactNativeStack-dev.js:2969:84
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
mountChildren
    ReactNativeStack-dev.js:2871:62
initializeChildren
    ReactNativeStack-dev.js:2940:45
mountComponent
    ReactNativeStack-dev.js:2969:84
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
performInitialMountWithErrorHandling
    ReactNativeStack-dev.js:1687:46
mountComponent
    ReactNativeStack-dev.js:1655:87
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
mountChildren
    ReactNativeStack-dev.js:2871:62
initializeChildren
    ReactNativeStack-dev.js:2940:45
mountComponent
    ReactNativeStack-dev.js:2969:84
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
mountChildren
    ReactNativeStack-dev.js:2871:62
initializeChildren
    ReactNativeStack-dev.js:2940:45
mountComponent
    ReactNativeStack-dev.js:2969:84
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54
mountComponent
    ReactNativeStack-dev.js:1655:184
mountComponent
    ReactNativeStack-dev.js:1327:53
performInitialMount
    ReactNativeStack-dev.js:1703:54

Example Code :

is attached
[result.js.txt](https://github.com/expo/vector-icons/files/1424605/result.js.txt)

**Comment by mikailcetinkaya** [comment]
`import React, { Component } from 'react';
import {  StyleSheet,Text,  View} from 'react-native';
import { Feather } from '@expo/vector-icons';

import Grid from 'react-native-grid-component';

export class Result extends Component {

  _renderItem = (data, i) => 
        <View style={[, styles.item]} key={i}>
            <Text>{i}:{data}<Feather name="eye" size='32'/>
            </Text> 
        </View>;


  render() {
    return (
      <Grid
        style={styles.list}
        renderItem={this._renderItem}
        data={this.props.data}
        itemsPerRow={10}
      />
    );
  }
}

const styles = StyleSheet.create({
  item: {
    flex: 1,
    margin: 1
  },
  list: {
    flex: 1
  },
});`

**Comment by brentvatne** [comment]
Hello! Install the latest version of expo (22.0.1) which comes bundled with the latest @expo/vector-icons (6.1.0) and includes the Feather icon font, and that will resolve your problem :)
