### ISSUE TITLE
Icons not showing up anymore

### ISSUE THREAD

**Issue by aymanMFD** [expo/vector-icons#301]
Previously the icons showed up without any problems, however now the icons doesn't work

This is the code:
```js
import { FontAwesome6 } from '@expo/vector-icons';
import { MaterialIcons } from '@expo/vector-icons';
// more code

function TabScreen() {
  return (
    <Tab.Navigator initialRouteName="Home"  screenOptions={({route}) => ({
      headerShown: false,
      tabBarInactiveTintColor: 'gray',
      tabBarActiveTintColor: '#00205E',
      tabBarIcon: ({color }) => {

        if (route.name === "Home") {
          return <FontAwesome6 name="house" size={20} color={color} />
        } else {
          return <MaterialIcons name="settings" size={24} color={color} />
        }
      }
    })} >
        <Tab.Screen name="Home" component={HomePage} />
        <Tab.Screen name="Settings" component={SettingsPage} options={{headerShown: true, headerShadowVisible: false}}/>
    </Tab.Navigator>
  )
}
```

**Comment by CobbyWS** [comment]
I'm experiencing the same issue.
The icons are displaying properly on Android but on iOS, 90% of them are displaying a square with a question mark in it.

It started when I upgraded from Expo version 50 to 51 and React Native 73 to 74.

An example of one that is showing the square with a question mark is FontAwesome5 `arrow-left`.

**Comment by imchivaa** [comment]
Try this

```npm install expo@latest```
```npx expo install --fix```

**Comment by Miloua91** [comment]
Try and install @react-native/assets-registry and add --clear flag when you start expo server if it doesn't work try changing your babel.config [like this ] https://github.com/callstack/react-native-paper/issues/4295#issuecomment-2000842264)

**Comment by aymanMFD** [comment]
I tried both 
`npm install expo@latest`
`npx expo install --fix`
and 
`npm install react-native/assets-registry`
and it fixed the issue thanks a lot guys

**Comment by appsgenie** [comment]
running into the same after upgrading to SDK 51..
seems like `react-native/assets-registry` already is there for me as some dependency to something else, do I still have to explicitly install it? if so, what does it do?

**Comment by barbugeorgedev** [comment]
had the same issue: update expo-font fixed it
