### ISSUE TITLE
No matter what, getting [TypeError: Cannot read property 'uri' of null] during dev mode

### ISSUE THREAD

**Issue by machinescream** [expo/vector-icons#304]
"@expo/vector-icons": "^14.0.2",
    "expo": "^51.0.12",

**Comment by stephancill** [comment]
Also seeing this

**Comment by machinescream** [comment]
> "@expo/vector-icons": "^14.0.2", "expo": "^51.0.12",
resolved by cleaned node_modules folder and update react native version
