### ISSUE TITLE
Invalid prop type

### ISSUE THREAD

**Issue by becnichelesmith** [expo/vector-icons#34]
Warning:
[exp] Warning: Failed prop type: Invalid prop `name` of value `puzzle-piece` supplied to `Icon`, expected one of ["ios-add","ios-add-circle","ios-add-circle-outline","ios-add-outline","ios-alarm","ios-alarm-outline","ios-albums","ios-albums-outline","ios-alert","ios-alert-outline","ios-american-football","ios-american-football-outline","ios-analytics","ios-analytics-outline","ios-aperture","ios-aperture-outline","ios-apps","ios-apps-outline","ios-appstore","ios-appstore-outline","ios-archive","ios-archive-outline","ios-arrow-back","ios-arrow-back-outline","ios-arrow-down","ios-arrow-down-outline","ios-arrow-dropdown","ios-arrow-dropdown-circle","ios-arrow-dropdown-circle-outline","ios-arrow-dropdown-outline","ios-arrow-dropleft","ios-arrow-dropleft-circle","ios-arrow-dropleft-circle-outline","ios-arrow-dropleft-outline","ios-arrow-dropright","ios-arrow-dropright-circle","ios-arrow-dropright-circle-outline","ios-arrow-dropright-outline","... [it lists all the icons that begin with ios and md] 

I'm trying to use an FA icon from the directory and am getting this error.

**Comment by becnichelesmith** [comment]
https://forums.expo.io/t/how-to-use-awesome-font/824

Solved!

**Comment by brentvatne** [comment]
👌
