### ISSUE TITLE
Docs: detail how to install module

### ISSUE THREAD

**Issue by morenoh149** [expo/vector-icons#35]
The readme points to https://docs.expo.io/versions/latest/guides/icons.html for installation instructions. But that page simply says `vector-icons` is installed with the demo app. How does one install this module if they did not start from the expo template app?

**Comment by brentvatne** [comment]
hm yeah we maybe have to explain in that doc that you don't need to install it. it is part of the `expo` package, so if you are using `expo` you can just import it and it will work as expected

**Comment by morenoh149** [comment]
wow you're right, all you have to do is
```js
import { Ionicons } from '@expo/vector-icons'
...
      <Ionicons name="md-checkmark-circle" size={32} color="green" />
```
