### ISSUE TITLE
Update fonts to their latest versions

### ISSUE THREAD

**Issue by outaTiME** [expo/vector-icons#43]
Hi guys, 
it would be great if you update each font to the latest versions, some are 2 years old.

Thanks !!!

**Comment by brentvatne** [comment]
we use the versions that are used by react-native-vector-icons: https://github.com/oblador/react-native-vector-icons

I'll update that to the latest, but it is pretty close already (4.4.2, latest upstream is 4.5.0)

**Comment by brentvatne** [comment]
ok i've updated this and it should land in next sdk of expo
