### ISSUE TITLE
Unable to run Material Icons

### ISSUE THREAD

**Issue by alexborton** [expo/vector-icons#46]
I am trying to include Material Icons with my Expo setup and just get the same error;

![simulator screen shot - iphone 6s - 2018-03-16 at 00 20 02](https://user-images.githubusercontent.com/1439507/37497731-334375c2-28b2-11e8-880e-7644f87872ee.png)

My App.js looks like this;

```
import React from 'react'
import { Font, AppLoading } from 'expo'
import { MaterialIcons } from '@expo/vector-icons'
import HybridApp from './src/App'

export default class NativeApp extends React.Component {
  constructor() {
    super()
    this.state = {
      fontsAreLoaded: false
    }
  }
  async componentWillMount() {
    await Font.loadAsync(MaterialIcons.font)
    this.setState({ fontsAreLoaded: true })
  }
  render() {
    const { fontsAreLoaded } = this.state
    return !fontsAreLoaded ? <AppLoading /> : <HybridApp />
  }
}
```

I am waiting to for the fonts to be loaded. Nothing doing :(

**Comment by Bonobomagno** [comment]
same error here.

**Comment by alexrborton** [comment]
I actually managed to fix this. It was to do with the way that React Native Elements was referring to the font. The clue was in the error - they call it `Material Icons` - not `MaterialIcons` as you might expect. 

Using the code above, but changing the call to the font to the below will work!

```
await Font.loadAsync({
  'Material Icons': require('@expo/vector-icons/fonts/MaterialIcons.ttf')
})
```

All we are doing is giving the font the correct name, `Material Icons` and call the .ttf directly from expo/vector-icons.

Hope that helps! Sorry i didn't post my solution sooner

**Comment by alexborton** [comment]
I actually managed to fix this. It was to do with the way that React Native Elements was referring to the font. The clue was in the error - they call it `Material Icons` - not `MaterialIcons` as you might expect.

Using the code above, but changing the call to the font to the below will work!

```
await Font.loadAsync({
  'Material Icons': require('@expo/vector-icons/fonts/MaterialIcons.ttf')
})
```

All we are doing is giving the font the correct name, `Material Icons` and call the .ttf directly from expo/vector-icons.

Hope that helps! Sorry i didn't post my solution sooner

**Comment by Bonobomagno** [comment]
This one worked also.
https://javascriptrambling.blogspot.it/2018/03/expo-icon-fonts-with-react-native-and.html
No problem on the naming in this way
