### ISSUE TITLE
Problem if there is a `+` in the path name

### ISSUE THREAD

**Issue by vjpr** [expo/vector-icons#47]
![screen shot 2018-03-21 at 7 34 02 pm](https://user-images.githubusercontent.com/281413/37730096-147ea3fa-2d3f-11e8-8caf-f26a6d9cd6ab.png)

# To reproduce

- Create new CRNA app
- Name the project folder `+foo`
- `npm start`
- Error...

**Comment by brentvatne** [comment]
hello, I think this is unrelated to vector-icons and some other underlying issue in the react-native packager (metro). I'd create the issue on that repo :)
