### ISSUE TITLE
Some font-awesome icons do not work

### ISSUE THREAD

**Issue by jarecsni** [expo/vector-icons#48]
Some font-awesome icons (smile, frown, etc.) don't seem to be supported by vector-icons (pls see related issue [1065](https://github.com/react-native-training/react-native-elements/issues/1065), also see [this snack](https://snack.expo.io/SkfVv2goG)).

Any plans to include the missing (new?) icons?

**Comment by brentvatne** [comment]
such an icon does not exist. it is called "smile-o"

<img width="731" alt="screen shot 2018-04-05 at 11 40 39 am" src="https://user-images.githubusercontent.com/90494/38385229-33063670-38c6-11e8-9304-90f12a3ff03e.png">
https://expo.github.io/vector-icons/

https://snack.expo.io/BJvT61NjG
