### ISSUE TITLE
Icons not being shown in detached project

### ISSUE THREAD

**Issue by fcaride** [expo/vector-icons#51]
Hi!,

When i make a release version in my IOS App the icons dont show up. This happens in my iphone and the simulator. If i run it in debug variant it works fine.

Any thought?

**Comment by fcaride** [comment]
In Android works fine but in IOS its not showing the icons.

**Comment by brentvatne** [comment]
hi! sorry I don't check this repo often and I missed this. If it's still an issue then please provide a reproducible example, nobody else has encountered this problem as far as I can tell
