### ISSUE TITLE
Missing at least one icon from Feather Icons

### ISSUE THREAD

**Issue by HughBerriez** [expo/vector-icons#54]
The **send** icon from https://feathericons.com/ is missing. This is my first issue submission, so let me know if I can help in anyway.

Thanks again for making such an awesome package!

**Comment by nicolas-adamini** [comment]
Same I would really appreciate if **send** from Feather was added !

**Comment by brentvatne** [comment]
It is in there now but not yet listed on the website, we need to re-deploy it
