### ISSUE TITLE
star-o icon

### ISSUE THREAD

**Issue by mischnic** [expo/vector-icons#55]
The `star-o` icon doesn't seem to exist, despite being listen on https://expo.github.io/vector-icons/.

(Same goes for the `star-off` & `star-outline` icons)

Code: 
```jsx
<MaterialIcons name="star-o" size={22} />
```

Version: 6.3.1
Error:

```
Warning: Failed prop type: Invalid prop `name` of value `star-o` supplied to `Icon`, expected one of 
["3d-rotation",
 ...
 "spellcheck","star","star-border","star-half","stars","stay-current-landscape"
 ...
]
```

**Comment by brentvatne** [comment]
star-o isn't a MaterialIcon, it's FontAwesome. Neither is star-off, it's a MaterialCommunityIcon
