### ISSUE TITLE
Is FontAwesome5 included? 

### ISSUE THREAD

**Issue by cmacdonnacha** [expo/vector-icons#58]
Hey, just wondering if FontAwesome5 is included in this? 

I see it is in react-native-vector-icons:
https://github.com/oblador/react-native-vector-icons/blob/master/FONTAWESOME5.md

**Comment by brentvatne** [comment]
It is not. I left it out because it seems too complex for just adding a font. There is a script to register with pro and some native code on iOS here: https://github.com/oblador/react-native-vector-icons/blob/9e756cb75ba770871ba0d12ee516adc47dbbb8d8/RNVectorIconsManager/RNVectorIconsManager.m#L180-L198

**Comment by hampustagerud** [comment]
Not sure it will help but I thought I'd let you know that [this PR](https://github.com/oblador/react-native-vector-icons/pull/808) removes the need for any manual setup. It uses swizzling on iOS which is not optimal but was the only way to get it to work fully until the Font Awesome team fixes their fonts (something is wrong with the metadata making it hard to use on iOS). This probably won't help with the Pro fonts but maybe enable the use of the standard icons?

Not an expo user so not sure if I helped anything here 🙂

**Comment by brentvatne** [comment]
thanks for that @hampustagerud! that looks a lot cleaner.

my only concern is that it still depends on `NativeIconAPI.getImageForFontAwesome5`. I think I'm missing some important context, from my point of view it's unclear why we need to have a native API to expose a font when the font icon set is, I believe, usable on the web just fine without it.

**Comment by hampustagerud** [comment]
There is ```NativeIconAPI.getImageForFont``` which is the backend of ```getImageSource``` which fetches a bitmap version of the icon. In order to support the different styles of Font Awesome 5 I needed to write a separate method on iOS which interprets the style and returns a bitmap based on the correct font. It is basically just a wrapper.

The [expo docs](https://docs.expo.io/versions/latest/guides/icons.html) doesn't mention ```getImageSource``` so there should not be any need to support this function either.

[This line](https://github.com/oblador/react-native-vector-icons/blob/908ca001b17c3219487404ae137b479d56733590/lib/create-icon-set-from-fontawesome5.js#L208) basically corresponds to [this line](https://github.com/oblador/react-native-vector-icons/blob/908ca001b17c3219487404ae137b479d56733590/lib/create-icon-set.js#L127) and is the only reference I make to the native module 🙂.

**Comment by rosnaib11** [comment]
I'm having trouble with this, I'm using expo  and I installed "native-base" and the "@expo/vector" but it throws me  an error. Its looking for /FontAwesome5

`[12:31:40] Unable to resolve "@expo/vector-icons/FontAwesome5" from "node_modules\native-base\dist\src\basic\IconNB.js"`

**Comment by rahamin1** [comment]
I am having the same problem...

Using expo version 31.
I was using Native-Base 2.8.0 and some 'ios-xxx-outline' icons didn't display correctly, but there were no problems in the build.
Following suggestions in various posts, I upgraded to 2.9.0 and then to 2.9.3.

This caused mu build to fail with the error:
`Unable to resolve "@expo/vector-icons/FontAwesome5" from "node_modules\native-base\dist\src\basic\IconNB.js"`

(I am not referring to FontAwesome5 anywhere in my code).

I tried to downgrade to 2.8.0, and ran `yarn`, I still have the problem. Tried to delete node-modules and rebuild, didn't help. So I am stuck now.
Any idea what to do?

Here is my package.json:
```
{
  "name": "my-new-project",
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "axios": "^0.18.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "expo": "^31.0.4",
    "firebase": "^5.5.1",
    "js-base64": "^2.4.9",
    "moment": "^2.22.2",
    "native-base": "^2.8.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz",
    "react-native-simple-radio-button": "^2.7.3",
    "react-native-snap-carousel": "^3.7.5",
    "react-navigation": "^2.18.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-logger": "^3.0.6",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0",
    "sentry-expo": "~1.9.0"
  },
  "devDependencies": {
    "babel-eslint": "^9.0.0",
    "eslint": "^5.6.0",
    "eslint-config-jquery": "^1.0.1",
    "eslint-plugin-flowtype": "^2.50.1",
    "eslint-plugin-html": "^4.0.6",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jquery": "^1.3.2",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.1",
    "jest-expo": "^31.0.0"
  }
}


```

**Comment by burtek** [comment]
@rahamin1 If you're using `2.9.x` and want to revert to `2.8.2` be sure to make it exactly `2.8.2`, not `^2.8.2` in `package.json` - `2.9.x` satisfies semver `^2.8.2` so the package won't be downgraded.

**Comment by rahamin1** [comment]
So my app is working with expo 31 and native-base 2.8.0, but breaks in 2.9.0 and newer versions without explicit references to FontAwesome5. Is this going to be fixed?

**Comment by JB-CHAUVIN** [comment]
Can you include it in a next version ?

**Comment by brentvatne** [comment]
no

**Comment by brentvatne** [comment]
I added a stub for FontAwesome5 that warns when it renders, but I don't plan to add support for FontAwesome5 as explained here.

**Comment by rahamin1** [comment]
@brentvatne Please forgive my ignorance:
how am I supposed to use this and make expo work using the new native-base version?

**Comment by wKovacs64** [comment]
@rahamin1 Update `@expo/vector-icons` to v8.1.0. The recent `native-base` versions will work after that.

**Comment by brentvatne** [comment]
if you're using sdk-31 you can delete yarn.lock or package-lock.json, delete node_modules, and run yarn or npm install again and it'll update to the latest version

**Comment by rahamin1** [comment]
Thanks Brent. Actually changing the version number of `@expo/vector-icons` in `package.json` and running `yarn` should be sufficient.

**Comment by blankse** [comment]
@brentvatne I have to include "@expo/vector-icons": "^9.0.0" for SDK 32 explicitly.
Without npm install the expo-font-fix branch.

@faustoct Do the following:
`npm install @expo/vector-icons@^9.0.0`

**Comment by faustoct** [comment]
@blankse 
I tried: `yarn add @expo/vector-icons@^9.0.0` it didn't worked.. after ran `npm install @expo/vector-icons@^9.0.0` cannot run react-native link without `npm install` it messed up confliting `yarn x npm` .

**Comment by faustoct** [comment]
@blankse it didn't work for me. Did you downgrade native-base@2.8.2?

**Comment by blankse** [comment]
Strange, no I have `native-base@^2.10.0`

**Comment by iamonuwa** [comment]
You need to install `@expo/vector-icons` separately

**Comment by DevinM6** [comment]
> @faustoct Do the following:
> `npm install @expo/vector-icons@^9.0.0`

Fixed my issue!

**Comment by Silva-Amon** [comment]
> You need to install `@expo/vector-icons` separately

It worked for me too. Thank you so much!

**Comment by bskinny129** [comment]
Installing @expo/vector-icons didn't work for me. I have tried several different versions, no install errors or warnings. Then when I run my app I get: "fontFamily "feather" is not a system font and has not been loaded through Font.loadAsync. - If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system. - If this is a custom font, be sure to load it with Font.loadAsync." (Loading the fonts myself in the code gives warnings that it has already been loaded)

```
"dependencies": {
        "@expo/vector-icons": "^9.0.0",
        "expo": "^32.0.0",
        "expo-font": "^2.0.0",
        "native-base": "2.8.2",
        "react": "16.5.0",
        "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
}
```
 
```
Expo CLI 2.7.0 environment info:
    System:
      OS: macOS 10.14.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.9.0 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.1.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.2 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.0.9 
    npmGlobalPackages:
      expo-cli: 2.7.0
```

**Comment by eddzmaciel** [comment]
@DevinM6  yeah, it works for me too!  ---> npm install @expo/vector-icons@^9.0.0

**Comment by vidurajith-darshana** [comment]
@DevinM6 It also worked for me as well! thanks

**Comment by mvanroon** [comment]
No need to install @expo/vector-icons@^9.0.0 separately. Keep your package.json clean and just remove node_modules and package-lock/yarn.lock, followed by an `npm install`. This will install 9.0.0.

**Comment by Jhony-Reyes** [comment]
> No need to install @expo/vector-icons@^9.0.0 separately. Keep your package.json clean and just remove node_modules and package-lock/yarn.lock, followed by an `npm install`. This will install 9.0.0.

By @mvanroon is the best fix

**Comment by A1M918** [comment]
> @rahamin1 Update `@expo/vector-icons` to v8.1.0. The recent `native-base` versions will work after that.

Solved my issue (y) thanks.

**Comment by avinashpatnaik** [comment]
@expo/vector-icons@^9.0.0 doesnt work for me..:(
