### ISSUE TITLE
Couldn't find preset "module:metro-react-native-babel-preset"

### ISSUE THREAD

**Issue by sievan** [expo/vector-icons#62]
... relative to directory  "[...] node_modules/react-native-vector-icons"

This seems to be caused by `react-native-vector-icons` and is fixed in `6.0.2` as seen in https://github.com/oblador/react-native-vector-icons/issues/865. I verified this by editing react-native-vector-icons' .babelrc as described in https://github.com/facebook/metro/issues/242#issuecomment-427639407, which fixes the problem.

**Comment by rollrodrig** [comment]
set it in .babelrc
"presets": ["react-native"]

**Comment by BenjaminWatts** [comment]
following this creates another error `Cannot find module 'AccessibilityInfo' (While processing preset: "/Users/me/nativeapp/node_modules/react-native/Libraries/react-native/react-native-implementation.js")`

**Comment by brentvatne** [comment]
I don't think any of this is related to @expo/vector-icons so I locked the issue. If you can somehow connect the errors you mentioned here to the library then open a new issue, thanks!
