### ISSUE TITLE
Some Icons from Ionicons is not working

### ISSUE THREAD

**Issue by mssio** [expo/vector-icons#63]
I have found out that ios-journal (Ionicons) icons from https://expo.github.io/vector-icons. Maybe there are some missing asset in this repository?

**Comment by brentvatne** [comment]
you need to update to @expo/vector-icons@8.0.0 to use everything from the website

**Comment by serranoarevalo** [comment]
Even after updating to 8.0.0 the icon 'md-tv' isn't working.

**Comment by brentvatne** [comment]
@serranoarevalo - I guess you may have updated it wrong? remember lockfiles

<img width="485" alt="screen shot 2018-10-15 at 10 45 13 am" src="https://user-images.githubusercontent.com/90494/46968185-6fc21780-d067-11e8-9dae-890f22280654.png">

https://github.com/brentvatne/lol-new-icons

**Comment by serranoarevalo** [comment]
@brentvatne  I reinstalled, restarted the server and it worked. Thanks for all the work you do man.

**Comment by i-schuetz** [comment]
How to update vector-icons, since the dependency isn't explicit? 
The only I see in my lock file is the types definition `"@types/expo__vector-icons@^6.2.3"`

Sorry, newbie...

**Comment by i-schuetz** [comment]
Ok, I just added it directly using `yarn add @expo/vector-icons@8.0.0`

But the problem I have now is that new icons are still not working (e.g. `check-circle`), apparently because the type definitions are outdates.

**Comment by brentvatne** [comment]
create issue and post code on snack.expo.io and i can look. from the error it seems like you're not using the MaterialCommunityIcons font component there
