### ISSUE TITLE
vector-icons is not working on ejected project

### ISSUE THREAD

**Issue by jackychanfox** [expo/vector-icons#64]
I ejected my project and generated signed apk.
In this app, the vector-icons are not loading.
what is problem?
help me! Thank you

**Comment by brentvatne** [comment]
you can just use react-native-vector-icons in an ejected project, no need to use this library

**Comment by ArfaouiHamouda** [comment]
i still has this problem now , even i  am  trying to use react-native-vector-icons it still asks for @expo/vector-icons as dependencie .
