### ISSUE TITLE
expose Toolbar android of react-native vector icons

### ISSUE THREAD

**Issue by sharanrprasad** [expo/vector-icons#65]
Hi, currently I am not able to access the ToolbarAndroid component of react-native-vector-icons from expo vector-icons. Is it possible to expose that?

**Comment by brentvatne** [comment]
for the same reason as https://github.com/expo/vector-icons/issues/26 we have no plan to expose this

ToolbarAndroid is not necessary, you can just use a view or some library like react-navigation
