### ISSUE TITLE
Not showing correct icons

### ISSUE THREAD

**Issue by infinityl00p** [expo/vector-icons#66]
Hi,

I've upgraded to the latest version of expo since expo no longer supported anything under version 24. Since updating, my icons have stopped appearing and/or are displaying the wrong characters. For example, I have:

```
<Ionicons name="md-checkmark-circle" size={50} color="#000" />
```
But all I see is a chinese character in it's place. I've hopped through forums spending hours trying to resolve this issue, I tried different fonts in @expo/vector-icons and it'll either show something random, nothing at all, or a box with a cross in it. 

Here's a list of relevant dependencies: 
```
	"dependencies": {
		"@expo/vector-icons": "^8.0.0",
		"expo": "^30.0.0",
		"react": "16.3.1",
		"react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
		"react-native-elements": "^0.19.1",
		"react-native-vector-icons": "^6.0.2",
	}
```

I've tested on both android and ios devices and i'm seeing the same issue. If any other details are required that may help give some more insight I will gladly provide it.

**Comment by brentvatne** [comment]
> If any other details are required that may help give some more insight I will gladly provide it.

provide a reproducible example. that exact code worked fine for me: https://github.com/brentvatne/lol-icons-again

create a new issue with a link to the repository that reproduces this when you can!
