### ISSUE TITLE
if size props is bigger than 25 after navigating between different screens ends up with blank screen

### ISSUE THREAD

**Issue by abkoyuncu** [expo/vector-icons#67]
Steps to reproduce:
1)Use stack navigation menu
2) Use icon with size bigger than 25 <Icon.Ionicons color={Colors.tabBar} size={26}
               name='ios-arrow-dropleft'/>
3)Open screen having component mentioned in 2nd step and navigate to another
4)Navigate back to previous screen

Result:
Blank screen displayed , you need to swipe down screen to see the content. If you make size 25 issue will not occur.

Versions:
    "expo": "^30.0.1",
    "lodash": "^4.17.11",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
    "react-navigation": "^2.16.0"

**Comment by brentvatne** [comment]
hey @abkoyuncu! can you please create an example on https://snack.expo.io/ and share it ehre? happy to look into it once you have that

**Comment by brentvatne** [comment]
create a new issue with a reproducible example when you have time
