### ISSUE TITLE
Lots of Ionicons gone since 8.0.0?

### ISSUE THREAD

**Issue by tn12787** [expo/vector-icons#69]
Lots of the outlined ios-*-outline icons seem to have gone since 8.0.0.

I'm not fully up-to-date, is there any reason for this? It's a little frustrating as a lot of my app's icons have broken consequentially.

**Comment by brentvatne** [comment]
I believe they were renamed in the latest release of the Ionicons font - you should be able to find an equivalent on https://expo.github.io/vector-icons/. We track the latest version of react-native-vector-icons which tries to keep all icon font families up to date.

**Comment by brentvatne** [comment]
from release notes:

> @expo/vector-icons has been updated to 8.0.0, adding support for AntDesign icons and updating other icons sets. We recommend you do a pass over your icons to make sure none of the names changed. The source code for the latest version can be found here.

**Comment by tn12787** [comment]
I did check the release notes, and had a look for my icons (in case of rename) but some seem to have disappeared entirely!

e.g. what was ios-bug-outline doesn't exist in https://expo.github.io/vector-icons/ (it hasn't been renamed, it's just **gone**).

I think this issue should be re-opened.

**Comment by brentvatne** [comment]
check out https://ionicons.com/ - there is no ios-bug-outline there

**Comment by brentvatne** [comment]
btw you can still use the older version if you want, just install it manually in your project

**Comment by tn12787** [comment]
They must have removed it for the new version. Sorry for the hassle! I'll roll back to older vector-icons for now while I come up with something better.

**Comment by tn12787** [comment]
Also, there are no tags on this repo, so I can't roll back to v7.0.0 - any ideas how I can get around this?

**Comment by brentvatne** [comment]
`npm show @expo/vector-icons@* version` will list all of the versions

**Comment by tn12787** [comment]
Thanks very much!
