### ISSUE TITLE
Error: Unable to resolve module ./fonts/Entypo.ttf (@exponent/vector-icons)

### ISSUE THREAD

**Issue by SeanAvery** [expo/vector-icons#7]
Having this issue with latest `@exponent/vetor-icons v4.0.0` 
Tested w/ `@expo/ex-navigation v2.9.2` and `@exponent/ex-navigation v2.9.1`

Code: example NavigationDrawer

Error Message:Unable to resolve module ./fonts/Entypo.ttf (@exponent/vector-icons)

I have also installed `react-native-vector-icons` which includes the Entypo library...

**Comment by JulianKingman** [comment]
I'm having the same issue.

**Comment by JulianKingman** [comment]
After a series of installing and uninstalling node_modules, `@expo/vector-icons`, restarting XDE, and restarting the simulator, it's working again.

**Comment by brentvatne** [comment]
@SeanAvery - what is in your exp.json?

**Comment by deathemperor** [comment]
I keep getting this error while building outside XDE:

```
error: bundling: UnableToResolveError: Unable to resolve module `./fonts/Entypo.ttf` from `/usr/local/Firebase-ReactNative/node_modules/@expo/vector-icons/Entypo.js`: Directory /usr/local/Firebase-ReactNative/node_modules/@expo/vector-icons/fonts/Entypo.ttf doesn't exist
    at Promise.resolve.then (/usr/local/Firebase-ReactNative/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:445:15)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

even though the /usr/local/Firebase-ReactNative/node_modules/@expo/vector-icons/fonts/Entypo.ttf is really there.

**Comment by dikaiosune** [comment]
@deathemperor what do you mean, "when building outside XDE?" In a detached/ExpoKit project?

**Comment by deathemperor** [comment]
@dikaiosune I'm trying "@expo/vector-icons" in a React Native project and run it normally not using the Expo app. Does this make it clearer?

**Comment by dikaiosune** [comment]
@deathemperor you don't want to do that, you should just be using `react-native-vector-icons` outside of the Expo client.

**Comment by Sofiane-13** [comment]
@deathemperor  @dikaiosune @brentvatne @JulianKingman @SeanAvery

**Comment by JulianKingman** [comment]
Check in node_modules to see if it actually exists first, then try clearing the various caches and restarting.

**Comment by jordanpapaleo** [comment]
Ok So this was closed but I do not see a concrete solution presented and yes, I just got the error  :)

What I have tried:

- `rm -rf node_modules; npm cache clear; npm i`
- `watchman watch-del-all`
- `./node_modules/react-native/packager/packager.sh --reset-cache`
- I verified the following files:
  - `node_modules/expo/node_modules/@expo/vector-icons/Entypo.js`
  - `node_modules/expo/node_modules/@expo/vector-icons/fonts/Entypo.tff`


Error Message:

```
UnableToResolveError: Unable to resolve module `./fonts/Entypo.ttf` from `/Users/**/node_modules/expo/node_modules/@expo/vector-icons/Entypo.js`: Directory /Users/**/node_modules/expo/node_modules/@expo/vector-icons/fonts/Entypo.ttf doesn't exist
```

I am using expo 16.0.0 with react native 0.44.0

**Comment by dikaiosune** [comment]
Is there a reason that you're using Expo 16.0.0 with RN 0.44? It's only compatible with 0.43.x.

**Comment by jordanpapaleo** [comment]
44 is what react native cli installed. It also fails with expo 17.

Do you think Expos issue with resolving node module paths is because of a react native minor semver bump?

**Comment by jordanpapaleo** [comment]
I tried with 43 too. The issue seems to be with using the standalone expo sdk install instead of through an expo build tool.

**Comment by dikaiosune** [comment]
@jordanpapaleo you definitely can't use the expo sdk without the expo build tools and the expo client. Can you provide more information about what you're trying here?

**Comment by jordanpapaleo** [comment]
I have a react native project and I wanted to use the GL Threejs support from expo.  So I just installed it.  Any way to make this work?

Thanks. 

Sent from my smallest computer

On May 21, 2017, at 7:05 AM, Adam Perry <notifications@github.com> wrote:

@jordanpapaleo you definitely can't use the expo sdk without the expo build tools and the expo client. Can you provide more information about what you're trying here?

**Comment by dikaiosune** [comment]
@jordanpapaleo no, sorry, it relies on a bunch of native code in the Expo client app.

**Comment by jordanpapaleo** [comment]
Thanks Adam :)

Sent from my smallest computer

On May 22, 2017, at 8:23 AM, Adam Perry <notifications@github.com> wrote:

@jordanpapaleo no, sorry, it relies on a bunch of native code in the Expo client app.

**Comment by JulianKingman** [comment]
Don't quote me on this, but I believe you can add expokit to an existing project. I can't find a link to how, but I remember seeing that somewhere.

**Comment by jordanpapaleo** [comment]
Gold ⭐️ to whoever finds it :)

Sent from my smallest computer

On May 22, 2017, at 12:34 PM, JulianKingman <notifications@github.com> wrote:

Don't quote me on this, but I believe you can add expokit to an existing project. I can't find a link to how, but I remember seeing that somewhere.

**Comment by babenzele** [comment]
@dikaiosune, that is very unfortunate. I was hoping to use Location and Permissions from expo in an ejected CRNA app. 

Any hope for a modular approach so people can import expo libs in more places? 

Here's hoping @JulianKingman finds that link in his browser history...

**Comment by brentvatne** [comment]
@babenzele - you can eject from CRNA with ExpoKit and continue to use those

**Comment by babenzele** [comment]
I ejected to regular React Native. 

https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md#ejecting-to-regular-react-native

**Comment by brentvatne** [comment]
> Any hope for a modular approach so people can import expo libs in more places?

as far as I know, no. this significantly increases maintenance and support costs.

why not just use expokit?

**Comment by JulianKingman** [comment]
https://medium.com/the-react-native-log/how-to-rename-a-react-native-app-dafd92161c35?source=linkShare-891791be2659-1497315900

**Comment by babenzele** [comment]
Pray tell, what is this expo kit you speak of? Could it be the solution I'm looking for?

**Comment by brentvatne** [comment]
> ExpoKit is an Objective-C and Java library that allows you to use the Expo platform with a native iOS/Android project.

https://docs.expo.io/versions/v17.0.0/guides/expokit.html :)

**Comment by babenzele** [comment]
I ejected to regular React Native, so it doesn't look like it's possible to just add it. 

From that page:

> There are two ways to get an ExpoKit project:
>
> - Create a pure-JS project in XDE, then use exp detach to add ExpoKit.
> - Create an app with create-react-native-app, then choose “eject with ExpoKit”.
>
> Make sure you follow one of the above paths before continuing in this guide. The remainder of the guide will assume you have created an ExpoKit project.

**Comment by brentvatne** [comment]
gotcha @babenzele - while it's possible to do this, we haven't written instructions yet for integrating expokit into existing apps so it might not be so easy for you. alternatively you could create a project, eject to expokit, then copy your code into it.
