### ISSUE TITLE
SimpleLineIcons not working on Android.

### ISSUE THREAD

**Issue by KentAgent** [expo/vector-icons#73]
So I have this issue with loading the SimpleLineIcons with Expo. I'm loading the fonts as required in the documentation. Everything loads and displays fine on iOS but it keeps crashing on Android (device & emulator).

This is the error message:
fontFamily 'SimpleLineIcons' is not a system font and has not been loaded through Font.loadAsync

I've gone in-depth of the issue over at stackoverflow. Heres a link to my question:
https://stackoverflow.com/questions/53329578/react-native-expo-fontfamily-simplelineicons-is-not-a-system-font-and-has-n

Any help would be muuch appreciated as I have been stuck with this problem for a long time.
Thanks a lot in advance!

**Comment by KentAgent** [comment]
Any update on this, internet? Still haven't managed to solve this unfortunately..

**Comment by brentvatne** [comment]
https://snack.expo.io/@notbrent/intelligent-truffles - here's an example, works as expected.

if you can share a reproducible example of your issue i can help!

**Comment by KentAgent** [comment]
> https://snack.expo.io/@notbrent/intelligent-truffles - here's an example, works as expected.
> 
> if you can share a reproducible example of your issue i can help!

Hello brentvatne and thx for your reply!
The suggested code almost solved my issue.
I ended up using a line like this:
'SimpleLineIcons': require('@expo/vector-icons/fonts/SimpleLineIcons.ttf')

Apparently android and iOS names their fonts in different manners so simple-line-icons on iOS and SimpleLineIcons on Android.

I assume using the line:
Font.loadAsync(SimpleLineIcons.font)
Is supposed to work as a cross-platform alternative but unfortunately I still got the same error on my Android emulator. That line is working for iOS though.

Anyways, thanks a lot for your help!

If anyone else has the same issue with loading any font and get the:
fontFamily: 'FontThatIsNotWorking' is not a system font and has not been loaded through Font.loadAsync.
Make sure you load your font in a similar way:
`componentDidMount() {
    this.loadAssetsAsync()
  }

  loadAssetsAsync = async () => {
    await Font.loadAsync({
      amaticBold: require('./assets/fonts/amaticSC-Bold.ttf'),
      indieFlower: require('./assets/fonts/indieFlower.ttf'),
      'Material Icons': require('@expo/vector-icons/fonts/MaterialIcons.ttf'),
      'MaterialIcons': require('@expo/vector-icons/fonts/MaterialIcons.ttf'),
      'SimpleLineIcons': require('@expo/vector-icons/fonts/SimpleLineIcons.ttf'),
      'simple-line-icons': require('@expo/vector-icons/fonts/SimpleLineIcons.ttf')
    })
    this.setState({ fontLoaded: true })
  }

  render() {
    const store = createStore(reducers, {}, applyMiddleware(ReduxThunk))

    if (!this.state.fontLoaded) {
      return <AppLoading />
    }

    return (
      <Provider store={store}>
        <Router />
      </Provider>
    )
  }`

There probably is a better way (using the Platform module from react-native for example) but if you're out of luck, try this and make sure you name your font >exactly< as the error message tells you.
As you can see in my example above I provide two different names for the same font. This is because iOS and Android want's them loaded in their specific way.
This really feels like an ugly solution, I know, but it works for now.

Good luck.

**Comment by KentAgent** [comment]
Hmm. I don't have the file by default (used CRNA).
In my .babelrc i have the following module:
{
  "presets": ["module:metro-react-native-babel-preset"]
}
but that's all.
Should this file be placed in root? Should it replace the .babelrc file? I can't see it in the repository you provided.

Actually the issue might be the way I'm using the font when I load in the icons.
I'm doing it in the following matter, not using the SimpleLineIcons module directly:
`
import React, { Component } from 'react'
import { View, TextInput, StyleSheet } from 'react-native'
import { Icon } from 'react-native-elements'

export default class InputIconField extends Component {

    constructor(props) {
        super(props)

        this.state = {
            inputString: ''
        }
    }

    render() {
        const colorStyle = this.props.colorStyle

        return (
            <View style={[styles.inputSection, { borderColor: colorStyle }]}>
                <Icon 
                    iconStyle={styles.iconStyle} 
                    name={this.props.iconName}
                    type={this.props.iconType} 
                    size={this.props.iconSize} 
                    color={colorStyle} 
                />
                <TextInput
                    style={[styles.input, { color: colorStyle } , this.props.textStyle]}
                    placeholder={this.props.placeholder}
                    placeholderTextColor={["#f4f9f4", this.props.placeholderTextColor]}
                    onChangeText={this.props.onChangeText}
                    underlineColorAndroid="transparent"
                    textContentType='none'
                    secureTextEntry={this.props.secureTextEntry}
                />
            </View>
        )
    }
}

const styles = StyleSheet.create({
    inputSection: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 5,
        borderBottomWidth: 1,
        //borderColor: '#f4f9f4',
        margin: 5,
        backgroundColor: 'transparent',
    },
    iconStyle: {
        padding: 10,
        marginLeft: 5,
        marginRight: 5,
    },
    input: {
        flex: 1,
        paddingTop: 10,
        paddingRight: 10,
        paddingBottom: 10,
        paddingLeft: 10,
        backgroundColor: 'transparent',
        color: '#f4f9f4',
        fontSize: 24,
        fontFamily: 'amaticBold'
    },
})

`
And where I implement it:

`
<InputIconField
            iconName="envelope"
            iconType="simple-line-icon"
            iconSize={iconSize}
            value={email}
            onChangeText={value => this.setState({ email: value })}
            placeholder="Email/Username"
            colorStyle={iconColor}
          />
`

Feels like I start to see the issue while I write this out..

Maybe this is the culprit? Using the <Icon /> from 'react-native-elements'

**Comment by brentvatne** [comment]
the babel preset should be babel-preset-expo. CRNA would add that not. sure where you got that babel preset that you're using from, it's the standard preset if you create a project with react-native init.

that InputIconField thing could be related. either way, not an issue with @expo/vector-icons :)
