### ISSUE TITLE
Missing package.json in vendor/react-native-vector-icons !

### ISSUE THREAD

**Issue by lc3t35** [expo/vector-icons#75]
When pod install (expo detached app), I have the following error message : 
```
Fetching podspec for 'RNVectorIcons` from `../node_modules/@expo/vector-icons/vendor/react-native-vector-icons'
[!] Failed to load 'RNVectorIcons' podspec: 
[!] Invalid 'RNVectorIcons.podspec' file: No such file or directory @ rb_sysopen - package.json.

 #  from /xxxx/node_modules/@expo/vector-icons/vendor/react-native-vector-icons/RNVectorIcons.podspec:2
 #  -------------------------------------------
 #  require 'json'
 >  version = JSON.parse(File.read('package.json'))["version"]
 #  
 #  -------------------------------------------
```

package.json is not in node_modules/@expo/vector-icons/vendor/react-native-vector-icons/ !!!

I get the one in https://github.com/oblador/react-native-vector-icons and error disappeared.

**Comment by brentvatne** [comment]
that is intentional.

you shouldn't link this. if you want to install react-native-vector-icons directly, add that to your project and don't use @expo/vector-icons

**Comment by lc3t35** [comment]
Reopened : I don't know why you changed this, it worked previously and it is needed by RNVectorIcons.podspec.
RNVectorIcons.podspec is using package.json since long (https://github.com/oblador/react-native-vector-icons/commit/23d406b748b52a2c7da9c64f184579833f178545#diff-17220c4291f422aa44eb6cba94d6a788), version 6.3.1 of expo/vector-icons has package.json file in vendor/react-native-vector-icons

**Comment by brentvatne** [comment]
the packager complains if package.json for react-native-vector-icons is there. you shouldn't use @expo/vector-icons to link react-native-vector-icons, i'd suggest using that library instead

**Comment by brentvatne** [comment]
no, you shouldn't need to link react-native-vector-icons at all in that case

**Comment by lc3t35** [comment]
So I explain again that I'm using @expo/vector-icons in my detached project (and I don't link react-native-vector-icons), I have the error message described above when I do "pod install" because package.json is missing in vendor/react-native-vector-icons. This error does not appear in 6.3.1 as package.json is included in this version and seems to have been removed later from later @expo/vector-icons versions. (I updated @expo/vector-icons following sdk31 upgrade instructions)

**Comment by brentvatne** [comment]
@lc3t35 - if you can provide a project that reproduces this problem i can look into it but it doesn't happen in a detached project for me so i don't know what to do

**Comment by lc3t35** [comment]
@brentvatne can you please show your package.json, Podfile of this detached project ?
I'm keeping `"@expo/vector-icons": "6.3.1"`in package.json and `pod 'RNVectorIcons', :path => '../node_modules/@expo/vector-icons/vendor/react-native-vector-icons'` in Podfile.
