### ISSUE TITLE
Ionicons with Jest not playing well together

### ISSUE THREAD

**Issue by jozsefDevs** [expo/vector-icons#78]
Hey Guys,

So I'm relatively new to Expo + React Native and it's working brilliantly so far. However there is one thing I can't resolve.

Whenever I'm trying to Snapshot test a component with Jest which contains an **Ionicons** element, the following error is thrown:
<img width="1073" alt="screenshot 2018-12-22 at 23 51 09" src="https://user-images.githubusercontent.com/4019391/50387559-82a83680-06ff-11e9-9f3a-c4d1c10491b8.png">

package.json (unrelated lines/packages removed)
```
{
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node_modules/.bin/jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^8.0.0",
    "expo": "^31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "jest-expo": "^31.0.0"
  }
}
```

Testicon.js
```
import React from 'react';
import { Text } from "native-base";
import { Ionicons} from "@expo/vector-icons";

export default function TestIcon(props){
    return (<React.Fragment><Text>Test thing</Text><Ionicons name="ios-arrow-forward" size={28} /></React.Fragment>);
}
```

TestIcon.spec.js
```
import React from 'react';
import TestIcon from '../../src/components/TestIcon';
import 'react-native';

import renderer from 'react-test-renderer';

it('should render', () => {
    const tree = renderer.create(<TestIcon />).toJSON();
    expect(tree).toMatchSnapshot();
});
```

ATM I can resolve this issue by totally removing the **Ionicons** tag from my component, then my test is running and the snapshot is saved as expected. 

Can you help me how can I resolve this one with leaving the Ionicons tag in my component?

**Comment by AlbuquerqueRafael** [comment]
Same problem here. Did you resolve this problem?

**Comment by jozsefDevs** [comment]
> Same problem here. Did you resolve this problem?

Unfortunately not sir. Maybe this is not a problem and it's my lack of experience with Jest, but I'm not even able to mock the Icon out. 👎

**Comment by c316** [comment]
I've setup a reproduction of the issue here, https://github.com/c316/vector-icon-issue-78

To run this, check it out, then do `npm test`

**Comment by brentvatne** [comment]
@c316 - the problem there is that you have this line in jest.config.js:

```
  transform: {
    '\\.js$': '<rootDir>/node_modules/react-native/jest/preprocessor.js'
  }
```

if you remove it, then it works. if you want to change that, check out https://github.com/expo/expo/blob/master/packages/jest-expo/jest-preset.json first and modify that rather than starting from scratch

**Comment by brentvatne** [comment]
to other people in this thread - this doesn't happen on a new tabs project, if you just replace `App.js` with the following code on a brand new project then tests will work as expected:

```js
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { AntDesign } from '@expo/vector-icons';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <AntDesign name="checkcircleo" size={20} color="black" />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center'
  }
});
```

so, look at your config and compare it with things in the preset (https://github.com/expo/expo/tree/master/packages/jest-expo) and see what you're overriding that might break it

**Comment by c316** [comment]
@brentvatne thanks for the fix. I'm not sure what that line was there for, but I'm glad to have it removed and working now.

**Comment by brentvatne** [comment]
for others in this thread also note how quickly we're able to help when you provide a reproducible example like @c316 did :)
