### ISSUE TITLE
App won't load due to icon; Font.isLoaded is not a function

### ISSUE THREAD

**Issue by Dygerati** [expo/vector-icons#79]
I'm trying to update my app after leaving it be for a sad amount of time. Right now I'm grappling with the error from the screenshot posted below. The code itself is pretty simple, and I'm not sure where to go with it:

```
import { FontAwesome, MaterialCommunityIcons } from '@expo/vector-icons';

 class Header extends React.Component {
 
   render() {
      const { navigate, state } = this.props.navProps.navigation;

      return (
         <View style={styles.headerContainer}>
               <TouchableOpacity
                  onPress={() => navigate(state.index === 1 ? 'DrawerClose' : 'DrawerOpen')}
               >
                  <MaterialCommunityIcons name="menu" />
               </TouchableOpacity>
         </View>
      );
   }
}
```
Expo: v31
@expo/vector-icons: 9.0.0

Any idea where to go with this?

![screenshot_20190105-144859](https://user-images.githubusercontent.com/444632/50730134-abb2c900-10fa-11e9-9cb0-1f4f83c3871f.jpg)

**Comment by Dygerati** [comment]
Annnnd nevermind. Just uninstalled the package (which is apparently now included in `expo`, and it works just fine.

**Comment by jeffreyongcay** [comment]
sewdrsf

**Comment by Dagaroth3exe** [comment]
which package? @joelclimbsthings
