### ISSUE TITLE
Error: Unable to  resolve module @expo/vector-icons/glyphmaps/Entypo.json

### ISSUE THREAD

**Issue by ricbermo** [expo/vector-icons#8]
```
UnhandledPromiseRejectionWarning:Unhandled promise rejection (rejection id: 1632): 
UnableToResolveError: Unable to resolve module @expo/vector-icons/glyphmaps/Entypo.json
from /home/user/Development/app/node_modules/@expo/vector-icons/Entypo.js:
Module does not exist in the module map or in these directories: 
/home/user/Development/app/node_modules/@expo/vector-icons/glyphmaps
```
This started happening when I changed from `exponent` to `expo`. With the `exponent` namespace everything is working fine

**Comment by ricbermo** [comment]
Solution is here https://www.reddit.com/r/reactnative/comments/62eth0/this_error_is_driving_me_insane_has_anyone_found/?st=J0X6G7QN&sh=e7d1076f

**Comment by delianides** [comment]
This is happening for us on a new project (created 4/2) and we can't figure out what started it.  Aside from the typical:
```
1. Clear watchman watches
2. Deleting the node_modules folder
3. Reset packager cache
```

Are there any other troubleshooting steps you'd suggest?

**Comment by ricbermo** [comment]
It started happening on my project when I tried to change `exponent` to `expo`. Try upgrading expo and the sdk to the latest possible.

**Comment by delianides** [comment]
@ricbermo we created the project on Sunday (4/2). Expo (15.0.3) and the SDK are the same version.

**Comment by ricbermo** [comment]
According to the redit link the issue is caused by `babel-plugin-module-resolver`. Please check version `2.5.0` is installed. Also, if you are using `yarn` clear its cache and install the dependencies using `npm`.

**Comment by delianides** [comment]
@ricbermo Yep, checked that too. Here is the [project](https://github.com/NewSpring/Junction-Native) is at  if you want to take a look.

**Comment by cseelus** [comment]
Same here, we tried everything from the Reddit link, [react-native issue 4968](https://github.com/facebook/react-native/issues/4968) and a bunch of other stuff, like different versions of Expo and switching between normal react-native and the Expo fork. Still getting 
![screen shot 2017-05-10 at 22 12 25](https://cloud.githubusercontent.com/assets/3188392/25919064/c7a9da86-35cd-11e7-91f7-5d130b6049ef.png)

**Comment by brentvatne** [comment]
did you change your babelrc? please use babel-preset-expo -- currently we don't support using `babel-plugin-module-alias` in addition to it as well.

https://github.com/expo/new-project-template/blob/master/.babelrc

**Comment by cseelus** [comment]
Thanks @brentvatne, that worked.

**Comment by kaulsalil88** [comment]
@brentvatne  the following is the content of my .babelrc ==> {
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": ["transform-react-jsx-source"]
    }
  }
}
In my package.json I have "babel-preset-expo": "^4.0.0"  . Do i need to upgrade that ??

**Comment by brentvatne** [comment]
just remove that from your package.json. the `expo` package includes the correct version of the preset

**Comment by kaulsalil88** [comment]
Got it working post adding the following depencies 
"babel-preset-expo": "^4.0.0", as a dev dependency 
 "react-native-svg": "^6.1.3", as a normal depency
