### ISSUE TITLE
Deprecation Warning in Import Font

### ISSUE THREAD

**Issue by mssio** [expo/vector-icons#80]
There is a problem in createIconSet.js files in this line:

`import * as Font from 'expo-font';`

 which produce deprecation warning:

> The syntax "import { Font } from 'expo-font'" is deprecated. Use "import * as Font from 'expo-font'" or import named exports instead. Support for the old syntax will be removed in SDK 33.

**Comment by brentvatne** [comment]
i imagine you have `@expo/vector-icons'` installed manually in your project. you can remove it, it's included in the expo package

**Comment by EKoetsjarjan** [comment]
thank you yarn remove @expo/vector-icons, did the job

**Comment by bencornwell** [comment]
Anyone got an example of how to then IMPORT said package from expo? This would be very useful context.

**Comment by bencornwell** [comment]
Thanks @EKoetsjarjan - this was a huge help!
` import {  Font } from 'expo'` 
solved the problem I was grappling with.
