### ISSUE TITLE
Expose TabBarItemIOS as done by react-native-vector-icons

### ISSUE THREAD

**Issue by alber70g** [expo/vector-icons#81]
It would be great if this was exposed. I've been working and sweating about 3 nights now just to come to the conclusion that the docs of `react-native-vector-icons` don't apply to the `@expo/vector-icons` because its **NOT ACTUALLY** wrapping the react-native counterpart.

<sup>
😠: Would be nice to state something like this, because things like this make me want to throw my MacBook out of the window...
</sup>

Can we please expose this somehow. I don't want to use the createTabBar from react-navigation: https://github.com/oblador/react-native-vector-icons/blob/master/lib/create-icon-set.js#L176

**Comment by brentvatne** [comment]
see https://github.com/expo/vector-icons/issues/5

react-native is about to remove TabBarIOS from the main repository as well. you should just use react-navigation's tab bar if you are using expo

**Comment by alber70g** [comment]
I don’t want all that navigation stuff, I just want the tabbar. And assign
simple actions to the button press. Isn’t there another way to achieve this
in a native way how the tab bar is used?

**Comment by brentvatne** [comment]
yup! you can use this: https://github.com/react-native-community/react-native-tab-view

**Comment by brentvatne** [comment]
if you did want to give react-navigation a try it's as simple as this to do tabs with it: https://snack.expo.io/@notbrent/tabs

**Comment by alber70g** [comment]
@brentvatne this looks promising. Thank you for this!

**Comment by alber70g** [comment]
I hope I'm not bothering too much, but I have another question. 

Is it possible to use the TabBarBottom without the navigation part? And if so, how?

**Comment by brentvatne** [comment]
react-navigation uses https://github.com/react-native-community/react-native-tab-view for that. i'd recommend just using the react-navigation version though because it has some built in styling improvements like support for tablet orientation
