### ISSUE TITLE
Feather, AntDesign, etc not working

### ISSUE THREAD

**Issue by faustoct** [expo/vector-icons#85]
tried 
````
import {AntDesign,Feather} from '@expo/vector-icons';
...
<Feather name='map-pin' />
````
it just gets a japense something on android and on iphone it renders a different icon. What's going on?

**Comment by brentvatne** [comment]
post a new issue with a reproducible example

**Comment by faustoct** [comment]
reproducible stuff
````
import {AntDesign,Feather} from '@expo/vector-icons';
render(){<View><Feather name='map-pin' /></View>}
````

@brentvatne 
it's a @expo/vector-icons + bare react-native. Is there something to do to load the fonts?

**Comment by faustoct** [comment]
moved to https://github.com/oblador/react-native-vector-icons

**Comment by brentvatne** [comment]
seems fine - https://snack.expo.io/@notbrent/suspicious-scone

**Comment by Pines-Cheng** [comment]
Can Bare React Native app use this package?
