### ISSUE TITLE
Rename font folder to match react-native-vector-icons

### ISSUE THREAD

**Issue by arqex** [expo/vector-icons#86]
Hi, first, thank you for such a great tool that makes my life easier every day!

I am trying to set up a react-native app that work for web too through react-native-web. When requiring the icons for the web using `@expo/vector-icons` I get errors, so I am using the original `react-native-vector-icons`.

My problem is that the `font` folder in react-native-vector-icons is called `Fonts` with a capital `F`. So the path can't be found in windows machines.

Could you update the folder name to match the react-native-vector-icon's one: `Fonts`.

Do you want me to create a PR?

Cheers

**Comment by brentvatne** [comment]
@EvanBacon has recently been working on web support for various pieces of expo sdk, including this lib. I believe this PR will solve your problem when it lands: https://github.com/expo/vector-icons/pull/84/files, but I'm not entirely sure I understand the issue so let me know if not

**Comment by arqex** [comment]
Those are great news! I think expo should play a main role in the convergence of web and native apps, so these updates are in the good direction.

Thanks!
