### ISSUE TITLE
Icons slow to display

### ISSUE THREAD

**Issue by lgngnr** [expo/vector-icons#90]
A few days ago  i generate an apk (./gradlew assembleRelease) and of that moment all the @expo/vector-icons/ became slow to display, i mean about a second or more when the app run first time. I try even to go some commit back and try to build the apk, maybe i add some code that slow the app but the icons still load very slowly. Any suggestion? it's a detached project

**Comment by brentvatne** [comment]
you should just use react-native-vector-icons directly in a detached project :)
