### ISSUE TITLE
 Unable to resolve "./vendor/react-native-vector-icons/glyphmaps/AntDesign.json" from "node_modules/@expo/vector-icons/AntDesign.js"

### ISSUE THREAD

**Issue by shinji1985** [expo/vector-icons#95]
I converted current my reactnative expo project into TypeScript code.
After I built the app with npm start and tried to open it in iOS simulator, then i run into the error below.

Unable to resolve "./vendor/react-native-vector-icons/glyphmaps/AntDesign.json" from "node_modules/@expo/vector-icons/AntDesign.js"

Could you anyone help me?

**Comment by shinji1985** [comment]
My package.json is as follows.

`
{
  "name": "app",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.1",
    "@types/expo__vector-icons": "^9.0.1",
    "axios": "^0.18.0",
    "expo": "^32.0.0",
    "native-base": "^2.12.1",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-elements": "^1.1.0",
    "react-native-expo-image-cache": "^3.2.0",
    "react-native-super-grid": "^3.0.4",
    "react-navigation": "^3.9.1"
  },
  "devDependencies": {
    "@types/expo": "^32.0.13",
    "@types/react-native": "^0.57.51",
    "babel-preset-expo": "^5.0.0",
    "typescript": "^3.4.5"
  },
  "private": true
}
`


I tried to add "resolveJsonModule" line in  tsconfig.json below
<img width="291" alt="スクリーンショット 2019-05-08 11 56 13" src="https://user-images.githubusercontent.com/2562290/57350457-54943200-7188-11e9-9d80-adeda68efcd6.png">
But nothing changed

**Comment by shinji1985** [comment]
sorry, when i reset cache with the command below, it works.
`expo r -c`

**Comment by thianlopezz** [comment]
Jeje
