### ISSUE TITLE
Warning: Failed prop type: Invalid prop `name` with Ionicons

### ISSUE THREAD

**Issue by YoucefMami** [expo/vector-icons#97]
Hi,

In https://www.npmjs.com/package/react-native-ionicons, we're given two ways to get icons for ios and android. I tried both approaches with v9.0.0 of this package.

I import Ionicons with this statement:
`import { Ionicons } from '@expo/vector-icons';`

1. Remove ios/md from the name eg 
`<Ionicons name="close-circle" size={25} style={{color: 'white'}} />`

I get the below error which also happens for other icon names:
_Warning: Failed prop type: Invalid prop `name` of value `close-circle` supplied to `Icon`, expected one of ..._ 

2. If I pass ios/android properties instead, the icon just does not show up but I get no warning eg:
`<Ionicons ios="ios-close-circle" android="md-close-circle" size={25} style={{color: 'white'}} />`

My current fix is based on https://stackoverflow.com/questions/52122061/how-can-i-create-cross-platform-icon-in-react-native. I use:
`<Ionicons name={`${Platform.OS === "ios" ? "ios" : "md"}-close-circle`} size={25} style={{color: 'white'}} />`

Is there a simpler way?

Thank you!

**Comment by YoucefMami** [comment]
Any suggestion?

**Comment by brentvatne** [comment]
i'm a bit confused, what is react-native-ionicons and how does it related to this repo?

**Comment by YoucefMami** [comment]
From the README:
This library is a compatibility layer around @oblador/react-native-vector-icons to work with the Expo asset system.

**Comment by YoucefMami** [comment]
Silly mistake on my part, sorry! The README clearly states:

> This library is a compatibility layer around @oblador/react-native-vector-icons to work with the Expo asset system.

I don't know how I confused this with react-native-ionicons. So, I guess the only way to get cross-platform icons is via:
`<Ionicons name={${Platform.OS === "ios" ? "ios" : "md"}-close-circle} size={25} style={{color: 'white'}} /> `
