### ISSUE TITLE
Icons don't render on Expo SDK v33.0.0 on Android

### ISSUE THREAD

**Issue by zaytrix** [expo/vector-icons#98]
When I run my project on the Expo app, on either iOS and Android, all the icons show up fine.

After I upgraded to Expo SDK v33.0.0, and ran `expo build:android`, and installed the apk, no icons are rendered on the standalone Android app.

They showed up just fine on the standalone Android app built with SDK v31.0.0.

On iOS they're working well.

Here's my `expo diagnostics`:
```console
Expo CLI 2.19.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.3.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 2.19.4
```

**Comment by brentvatne** [comment]
I believe this is related to https://github.com/expo/expo/issues/4474

In your project, run `expo install expo-font expo-asset expo-constants` do another publish/build

**Comment by yaron1m** [comment]
This worked for me!
Just one thing - I had to do another build (publish did not work)

Thanks @brentvatne !

**Comment by brentvatne** [comment]
:+1:

we have now changed the behavior described in #4474 to be the same as before, so you don't have to have these packages in your app. we'll add back the behavior to include only the parts of the sdk that you use later on after more testing. you can opt back into it now using `expo build:android -t app-bundle` but you need to enable app signing in the google play developer console to do so, and we don't have documentation written for it yet.
